
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import openpyxl
import math 


class Ui_ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE(object):


    def calculer_engrenage(self):
        try:

            M = float(self.lineEdit1.text())
            A_P = float(self.lineEdit2.text())
            Σ = float(self.lineEdit3.text())
            b = float(self.lineEdit4.text())    
            Z1 = int(self.lineEdit5.text())
            Z2 = int(self.lineEdit6.text())             
                      
            Jn = 0
            C = 0
            x1 = 0
            x2 = 0

            U = Z2/Z1

            i = Z1/Z2

            d1 = Z1*M 
            d2 = Z2*M   

            ha1 = float(1+x1)*M
            ha2 = float(1+x2)*M

            hf1 = float(1.25+C-x1)*M
            hf2 = float(1.25+C-x2)*M

            h = 2.25*M

            δ11 = math.atan(math.sin(math.radians(Σ)) / ((Z2/Z1)+(math.cos(math.radians(Σ)))))
            δ1 = math.degrees(δ11)

            δ22 = math.atan(math.sin(math.radians(Σ)) / ((Z1/Z2)+(math.cos(math.radians(Σ)))))
            δ2 = math.degrees(δ22)

            R = (0.5*d1) / math.sin(math.radians(δ1))

            θ11 = math.atan(ha1/R)
            θa1 = math.degrees(θ11)

            θ22 = math.atan(ha2/R)
            θa2 = math.degrees(θ22)

            θf11 = math.atan(hf1/R)
            θf1 = math.degrees(θf11)

            θf22 = math.atan(hf2/R)
            θf2 = math.degrees(θf22)

            δa1 = δ1 + θa1

            δa2 = δ2 + θa2

            δf1 = δ1 - θf1

            δf2 = δ2 - θf2

            Rm = R - b/2

            Ri = R - b

            mn = (M*Rm)/R

            
            s1 = M*((math.pi/2)+ 2* x1* math.tan(math.radians(A_P))) - 0.5*Jn
            s2 = M*((math.pi/2)+ 2* x2* math.tan(math.radians(A_P))) - 0.5*Jn

            SC1 = s1*(1-C*(s1/d1)**2)
            SC2 = s2*(1-C*(s2/d2)**2)

            ham1 = ha1 + 0.25*((SC1**2)/d1)*math.cos(math.radians(δ1))
            ham2 = ha2 + 0.25*((SC2**2)/d2)*math.cos(math.radians(δ2))

            da1 =  d1 + 2* ha1 *math.cos(math.radians(δ1))
            da2 =  d2 + 2* ha2 *math.cos(math.radians(δ2))

            df1 = d2 -2* hf1* math.cos(math.radians(δ1))
            df2 = d2 -2* hf2* math.cos(math.radians(δ2))

            dai1 = da1* (Ri/R)
            dai2 = da2* (Ri/R)

            dv1 = d1/math.cos(math.radians(δ1))
            dv2 = d2/math.cos(math.radians(δ2))

            av = (dv1 + dv2)/ 2

            dav1 = dv1+2*ha1
            dav2 = dv2+2*ha2

            dfv1 = dv1-2*hf1
            dfv2 = dv2-2*hf2

            dbv1 = dv1*math.cos(math.radians(A_P))
            dbv2 = dv2*math.cos(math.radians(A_P))

            αav11 = float(math.acos((dbv1/dav1)))
            αav22 = float(math.acos((dbv2/dav2)))
            αav1 = math.degrees(αav11)
            αav2 = math.degrees(αav22)

            zv1 = Z1/math.cos(math.radians(δ1))
            zv2 = Z2/math.cos(math.radians(δ2))

            εv1 = (zv1/(2*math.pi))*(math.tan(math.radians(αav1))-math.tan(math.radians(A_P)))
            εv2 = (zv2/(2*math.pi))*(math.tan(math.radians(αav2))-math.tan(math.radians(A_P)))

            εv = εv1 + εv2

            gav1 = εv1*math.pi*M*math.cos(math.radians(A_P))
            gav2 = εv2*math.pi*M*math.cos(math.radians(A_P))

            gv = gav1 + gav2
        except ValueError:
            QMessageBox.warning(None, "Erreur de saisie", "Il est impossible d'effectuer le calcul. Vérifiez les valeurs d'entrée.")
            return
        except ZeroDivisionError:
            QMessageBox.warning(None, "Erreur de saisie", "Il est impossible d'effectuer le calcul. Vérifiez les valeurs d'entrée.")
            return

        # Affichage des resultats dans les LineEdit
        self.lineEdit9.setText(str(U))
        self.lineEdit10.setText(str(i))
        self.lineEdit11.setText(str(d1))
        self.lineEdit12.setText(str(d2))
        self.lineEdit13.setText(str(ha1))
        self.lineEdit14.setText(str(ha2))
        self.lineEdit15.setText(str(hf1))
        self.lineEdit16.setText(str(hf2))
        self.lineEdit17.setText(str(h))
        self.lineEdit18.setText(str(δ1))
        self.lineEdit19.setText(str(δ2))
        self.lineEdit20.setText(str(R))
        self.lineEdit21.setText(str(θa1))
        self.lineEdit22.setText(str(θa2))
        self.lineEdit23.setText(str(θf1))
        self.lineEdit24.setText(str(θf2))
        self.lineEdit25.setText(str(δa1))
        self.lineEdit26.setText(str(δa2))
        self.lineEdit27.setText(str(δf1))
        self.lineEdit28.setText(str(δf2))
        self.lineEdit29.setText(str(Rm))
        self.lineEdit30.setText(str(Ri))
        self.lineEdit31.setText(str(mn))
        self.lineEdit32.setText(str(s1))
        self.lineEdit33.setText(str(s2))
        self.lineEdit34.setText(str(SC1))
        self.lineEdit35.setText(str(SC2))
        self.lineEdit36.setText(str(ham1))
        self.lineEdit37.setText(str(ham2))
        self.lineEdit38.setText(str(da1))
        self.lineEdit39.setText(str(da2))
        self.lineEdit40.setText(str(df1))
        self.lineEdit41.setText(str(df2))
        self.lineEdit42.setText(str(dai1))
        self.lineEdit43.setText(str(dai2))
        self.lineEdit44.setText(str(dv1))
        self.lineEdit45.setText(str(dv2))
        self.lineEdit46.setText(str(av))
        self.lineEdit47.setText(str(dav1))
        self.lineEdit48.setText(str(dav2))
        self.lineEdit49.setText(str(dfv1))
        self.lineEdit50.setText(str(dfv2))
        self.lineEdit51.setText(str(dbv1))
        self.lineEdit52.setText(str(dbv2))
        self.lineEdit53.setText(str(αav1))
        self.lineEdit54.setText(str(αav2))
        self.lineEdit55.setText(str(zv1))
        self.lineEdit56.setText(str(zv2))
        self.lineEdit57.setText(str(εv1))
        self.lineEdit58.setText(str(εv2))
        self.lineEdit59.setText(str(εv))
        self.lineEdit60.setText(str(gav1))
        self.lineEdit61.setText(str(gav2))
        self.lineEdit62.setText(str(gv))

    def sauvegarder_dans_excel(self):
        wb = openpyxl.Workbook()
        ws = wb.active

        noms_labels = [
            self.label1.text(),
            self.label2.text(),
            self.label3.text(),
            self.label4.text(),
            self.label5.text(),
            self.label5.text(),
            self.label7.text(),
            self.label8.text(),
            self.label9.text(),
            self.label9.text(),
            self.label10.text(),
            self.label10.text(),
            self.label11.text(),
            self.label11.text(),
            self.label12.text(),
            self.label13.text(),
            self.label13.text(),
            self.label14.text(),
            self.label15.text(),
            self.label15.text(),
            self.label16.text(),
            self.label16.text(),
            self.label17.text(),
            self.label17.text(),
            self.label18.text(),
            self.label18.text(),
            self.label19.text(),
            self.label20.text(),
            self.label21.text(),
            self.label22.text(),
            self.label22.text(),
            self.label23.text(),
            self.label23.text(),
            self.label24.text(),
            self.label24.text(),
            self.label25.text(),
            self.label25.text(),
            self.label26.text(),
            self.label26.text(),
            self.label27.text(),
            self.label27.text(),
            self.label28.text(),
            self.label28.text(),
            self.label29.text(),
            self.label30.text(),
            self.label30.text(),
            self.label31.text(),
            self.label31.text(),
            self.label32.text(),
            self.label32.text(),
            self.label33.text(),
            self.label33.text(),
            self.label34.text(),
            self.label34.text(),
            self.label35.text(),
            self.label35.text(),
            self.label36.text(),
            self.label37.text(),
            self.label37.text(),
            self.label38.text(),
        ]

        symboles = [
            'm', '∝', 'Σ', 'b', 'Z1', 'Z2','U', 'i', 
            'd1', 'd2', 'ha1', 'ha2', 'hf1', 'hf2', 'h' ,'δ1', 'δ2', 'R',
            'θa1', 'θa2', 'θf1', 'θf2', 'δa1','δa2','δf1', 'δf2', 'Rm', 'Ri', 
            'mn', 's1', 's2', 'SC1', 'SC2', 'ham1','ham2', 'da1', 'da2', 'df1', 
            'df2', 'dai1', 'dai2', 'dv1', 'dv2', 'av','dav1', 'dav2', 'dfv1', 'dfv2', 
            'dbv1', 'dbv2', 'αav1', 'αav2', 'zv1', 'zv2','εv1', 'εv2','εv', 'gav1',
            'gav2', 'gv'
            
        ]


        valeurs = [

            self.lineEdit1.text(),
            self.lineEdit2.text(),
            self.lineEdit3.text(),
            self.lineEdit4.text(),   
            self.lineEdit5.text(),
            self.lineEdit6.text(),
            self.lineEdit9.text(),
            self.lineEdit10.text(),
            self.lineEdit11.text(),
            self.lineEdit12.text(),
            self.lineEdit13.text(),
            self.lineEdit14.text(),
            self.lineEdit15.text(),
            self.lineEdit16.text(),
            self.lineEdit17.text(),
            self.lineEdit18.text(),
            self.lineEdit19.text(),
            self.lineEdit20.text(),
            self.lineEdit21.text(),
            self.lineEdit22.text(),
            self.lineEdit23.text(),
            self.lineEdit24.text(),
            self.lineEdit25.text(),
            self.lineEdit26.text(),
            self.lineEdit27.text(),
            self.lineEdit28.text(),
            self.lineEdit29.text(),
            self.lineEdit30.text(),
            self.lineEdit31.text(),
            self.lineEdit32.text(),
            self.lineEdit33.text(),
            self.lineEdit34.text(),
            self.lineEdit35.text(),
            self.lineEdit36.text(),
            self.lineEdit37.text(),
            self.lineEdit38.text(),
            self.lineEdit39.text(),
            self.lineEdit40.text(),
            self.lineEdit41.text(),
            self.lineEdit42.text(),
            self.lineEdit43.text(),
            self.lineEdit44.text(),
            self.lineEdit45.text(),
            self.lineEdit46.text(),
            self.lineEdit47.text(),
            self.lineEdit48.text(),
            self.lineEdit49.text(),
            self.lineEdit50.text(),
            self.lineEdit51.text(),
            self.lineEdit52.text(),
            self.lineEdit53.text(),
            self.lineEdit54.text(),
            self.lineEdit55.text(),
            self.lineEdit56.text(),
            self.lineEdit57.text(),
            self.lineEdit58.text(),
            self.lineEdit59.text(),
            self.lineEdit60.text(),
            self.lineEdit61.text(),
            self.lineEdit62.text(),

            
        ]

        unites = [

            'mm', 'degré', 'degré', 'mm', '', '', '', '', 
            'mm', 'mm', 'mm', 'mm', 'mm', 'mm', 'mm', 'degré', 'degré', 'mm',
            'degré', 'degré', 'degré', 'degré', 'degré', 'degré', 'degré', 'degré', 'mm', 'mm', 
            'mm', 'mm', 'mm', 'mm', 'mm', 'mm', 'mm', 'mm', 'mm' , 'mm',
            'mm', 'mm', 'mm', 'mm', 'mm', 'mm', 'mm', 'mm', 'mm', 'mm',
            'mm', 'mm', 'degré', 'degré', '', '', '', '', '', 'mm',
            'mm', 'mm'

        ]

        entete = ['Nom(s)', 'Symbole(s)', 'Valeur(s)', 'Unité(s)']
        ws.append(entete)

        for i in range(len(noms_labels)):
            ws.append([noms_labels[i], symboles[i], valeurs[i], unites[i]])

        for row in ws.iter_rows(min_row=1, max_row=61, min_col=1, max_col=4):
            for cell in row:
                cell.border = openpyxl.styles.Border(
                    left=openpyxl.styles.Side(border_style='thin'),
                    right=openpyxl.styles.Side(border_style='thin'),
                    top=openpyxl.styles.Side(border_style='thin'),
                    bottom=openpyxl.styles.Side(border_style='thin')
                )

        for row in ws.iter_rows(min_row=1, max_row=1, min_col=1, max_col=4):
            for cell in row:
                cell.fill = openpyxl.styles.PatternFill(start_color="0070C0", end_color="0070C0", fill_type="solid")
                cell.font = openpyxl.styles.Font(color="FFFFFF", bold=True)


        file_path, _ = QtWidgets.QFileDialog.getSaveFileName(None, "Enregistrer le fichier Excel", "", "Excel Files (*.xlsx)")
        if file_path:
            wb.save(file_path)
            QtWidgets.QMessageBox.information(None, "Enregistrement", "Fichier Excel enregistré avec succès !")







    def setupUi(self, ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE):
        ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE.setObjectName("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE")
        ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE.resize(550, 372)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("reducteur_gearexpert.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 523, 1358))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 4, 1, 1, 1)
        self.label5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label5.setFont(font)
        self.label5.setObjectName("label5")
        self.gridLayout_2.addWidget(self.label5, 4, 0, 1, 1)
        self.label_154 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_154.setFont(font)
        self.label_154.setObjectName("label_154")
        self.gridLayout_2.addWidget(self.label_154, 2, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 1, 1, 1, 1)
        self.label1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.gridLayout_2.addWidget(self.label1, 0, 0, 1, 1)
        self.label2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.gridLayout_2.addWidget(self.label2, 1, 0, 1, 1)
        self.lineEdit6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit6.setFont(font)
        self.lineEdit6.setObjectName("lineEdit6")
        self.gridLayout_2.addWidget(self.lineEdit6, 4, 4, 1, 1)
        self.lineEdit1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit1.setFont(font)
        self.lineEdit1.setObjectName("lineEdit1")
        self.gridLayout_2.addWidget(self.lineEdit1, 0, 2, 1, 1)
        self.label3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.gridLayout_2.addWidget(self.label3, 2, 0, 1, 1)
        self.lineEdit2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit2.setFont(font)
        self.lineEdit2.setObjectName("lineEdit2")
        self.gridLayout_2.addWidget(self.lineEdit2, 1, 2, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.gridLayout_2.addWidget(self.label_46, 4, 3, 1, 1)
        self.lineEdit5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit5.setFont(font)
        self.lineEdit5.setObjectName("lineEdit5")
        self.gridLayout_2.addWidget(self.lineEdit5, 4, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 0, 1, 1, 1)
        self.label4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label4.setFont(font)
        self.label4.setObjectName("label4")
        self.gridLayout_2.addWidget(self.label4, 3, 0, 1, 1)
        self.lineEdit4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit4.setFont(font)
        self.lineEdit4.setObjectName("lineEdit4")
        self.gridLayout_2.addWidget(self.lineEdit4, 3, 2, 1, 1)
        self.lineEdit3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit3.setFont(font)
        self.lineEdit3.setObjectName("lineEdit3")
        self.gridLayout_2.addWidget(self.lineEdit3, 2, 2, 1, 1)
        self.label_170 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_170.setFont(font)
        self.label_170.setObjectName("label_170")
        self.gridLayout_2.addWidget(self.label_170, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setMaximumSize(QtCore.QSize(180, 180))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.calculer_engrenage) # Liaison du clic du bouton à la fonction de calcul
        ############################################################################################################

        self.verticalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")

        self.pushButton_3.clicked.connect(self.sauvegarder_dans_excel)  # Connecte le clic du bouton à la fonction de sauvegarde
        ################################################################################################################
        
        self.verticalLayout.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        self.label_45 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.verticalLayout.addWidget(self.label_45, 0, QtCore.Qt.AlignHCenter)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem4)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_175 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_175.setFont(font)
        self.label_175.setObjectName("label_175")
        self.gridLayout_3.addWidget(self.label_175, 6, 3, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.gridLayout_3.addWidget(self.label_41, 4, 1, 1, 1)
        self.label_174 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_174.setFont(font)
        self.label_174.setObjectName("label_174")
        self.gridLayout_3.addWidget(self.label_174, 6, 1, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.gridLayout_3.addWidget(self.label_63, 5, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.gridLayout_3.addWidget(self.label_53, 3, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.gridLayout_3.addWidget(self.label_55, 16, 1, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.gridLayout_3.addWidget(self.label_67, 12, 1, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.gridLayout_3.addWidget(self.label_49, 15, 3, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_72.setFont(font)
        self.label_72.setObjectName("label_72")
        self.gridLayout_3.addWidget(self.label_72, 15, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.gridLayout_3.addWidget(self.label_59, 13, 1, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.gridLayout_3.addWidget(self.label_69, 2, 3, 1, 1)
        self.label_184 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_184.setFont(font)
        self.label_184.setObjectName("label_184")
        self.gridLayout_3.addWidget(self.label_184, 30, 3, 1, 1)
        self.label_182 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_182.setFont(font)
        self.label_182.setObjectName("label_182")
        self.gridLayout_3.addWidget(self.label_182, 30, 1, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_81.setFont(font)
        self.label_81.setObjectName("label_81")
        self.gridLayout_3.addWidget(self.label_81, 31, 1, 1, 1)
        self.label_183 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_183.setFont(font)
        self.label_183.setObjectName("label_183")
        self.gridLayout_3.addWidget(self.label_183, 25, 1, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_71.setFont(font)
        self.label_71.setObjectName("label_71")
        self.gridLayout_3.addWidget(self.label_71, 14, 1, 1, 1)
        self.lineEdit20 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit20.setFont(font)
        self.lineEdit20.setObjectName("lineEdit20")
        self.gridLayout_3.addWidget(self.lineEdit20, 7, 2, 1, 1)
        self.lineEdit21 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit21.setFont(font)
        self.lineEdit21.setObjectName("lineEdit21")
        self.gridLayout_3.addWidget(self.lineEdit21, 8, 2, 1, 1)
        self.lineEdit12 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit12.setFont(font)
        self.lineEdit12.setObjectName("lineEdit12")
        self.gridLayout_3.addWidget(self.lineEdit12, 2, 4, 1, 1)
        self.lineEdit18 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit18.setFont(font)
        self.lineEdit18.setObjectName("lineEdit18")
        self.gridLayout_3.addWidget(self.lineEdit18, 6, 2, 1, 1)
        self.lineEdit16 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit16.setFont(font)
        self.lineEdit16.setObjectName("lineEdit16")
        self.gridLayout_3.addWidget(self.lineEdit16, 4, 4, 1, 1)
        self.lineEdit14 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit14.setFont(font)
        self.lineEdit14.setObjectName("lineEdit14")
        self.gridLayout_3.addWidget(self.lineEdit14, 3, 4, 1, 1)
        self.lineEdit19 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit19.setFont(font)
        self.lineEdit19.setObjectName("lineEdit19")
        self.gridLayout_3.addWidget(self.lineEdit19, 6, 4, 1, 1)
        self.lineEdit17 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit17.setFont(font)
        self.lineEdit17.setObjectName("lineEdit17")
        self.gridLayout_3.addWidget(self.lineEdit17, 5, 2, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_70.setFont(font)
        self.label_70.setObjectName("label_70")
        self.gridLayout_3.addWidget(self.label_70, 11, 3, 1, 1)
        self.label_178 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_178.setFont(font)
        self.label_178.setObjectName("label_178")
        self.gridLayout_3.addWidget(self.label_178, 10, 1, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.gridLayout_3.addWidget(self.label_54, 27, 3, 1, 1)
        self.label_181 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_181.setFont(font)
        self.label_181.setObjectName("label_181")
        self.gridLayout_3.addWidget(self.label_181, 20, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.gridLayout_3.addWidget(self.label_44, 20, 3, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_77.setFont(font)
        self.label_77.setObjectName("label_77")
        self.gridLayout_3.addWidget(self.label_77, 22, 1, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_80.setFont(font)
        self.label_80.setObjectName("label_80")
        self.gridLayout_3.addWidget(self.label_80, 28, 3, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_79.setFont(font)
        self.label_79.setObjectName("label_79")
        self.gridLayout_3.addWidget(self.label_79, 24, 3, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.gridLayout_3.addWidget(self.label_66, 29, 1, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.gridLayout_3.addWidget(self.label_64, 28, 1, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_76.setFont(font)
        self.label_76.setObjectName("label_76")
        self.gridLayout_3.addWidget(self.label_76, 21, 1, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_78.setFont(font)
        self.label_78.setObjectName("label_78")
        self.gridLayout_3.addWidget(self.label_78, 23, 3, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.gridLayout_3.addWidget(self.label_58, 23, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.gridLayout_3.addWidget(self.label_57, 24, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.gridLayout_3.addWidget(self.label_43, 21, 3, 1, 1)
        self.lineEdit55 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit55.setFont(font)
        self.lineEdit55.setObjectName("lineEdit55")
        self.gridLayout_3.addWidget(self.lineEdit55, 27, 2, 1, 1)
        self.lineEdit54 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit54.setFont(font)
        self.lineEdit54.setObjectName("lineEdit54")
        self.gridLayout_3.addWidget(self.lineEdit54, 26, 4, 1, 1)
        self.lineEdit57 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit57.setFont(font)
        self.lineEdit57.setObjectName("lineEdit57")
        self.gridLayout_3.addWidget(self.lineEdit57, 28, 2, 1, 1)
        self.lineEdit56 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit56.setFont(font)
        self.lineEdit56.setObjectName("lineEdit56")
        self.gridLayout_3.addWidget(self.lineEdit56, 27, 4, 1, 1)
        self.lineEdit61 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit61.setFont(font)
        self.lineEdit61.setObjectName("lineEdit61")
        self.gridLayout_3.addWidget(self.lineEdit61, 30, 4, 1, 1)
        self.lineEdit53 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit53.setFont(font)
        self.lineEdit53.setObjectName("lineEdit53")
        self.gridLayout_3.addWidget(self.lineEdit53, 26, 2, 1, 1)
        self.lineEdit60 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit60.setFont(font)
        self.lineEdit60.setObjectName("lineEdit60")
        self.gridLayout_3.addWidget(self.lineEdit60, 30, 2, 1, 1)
        self.lineEdit62 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit62.setFont(font)
        self.lineEdit62.setObjectName("lineEdit62")
        self.gridLayout_3.addWidget(self.lineEdit62, 31, 2, 1, 1)
        self.lineEdit59 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit59.setFont(font)
        self.lineEdit59.setObjectName("lineEdit59")
        self.gridLayout_3.addWidget(self.lineEdit59, 29, 2, 1, 1)
        self.lineEdit58 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit58.setFont(font)
        self.lineEdit58.setObjectName("lineEdit58")
        self.gridLayout_3.addWidget(self.lineEdit58, 28, 4, 1, 1)
        self.lineEdit11 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit11.setFont(font)
        self.lineEdit11.setObjectName("lineEdit11")
        self.gridLayout_3.addWidget(self.lineEdit11, 2, 2, 1, 1)
        self.label23 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label23.setFont(font)
        self.label23.setObjectName("label23")
        self.gridLayout_3.addWidget(self.label23, 16, 0, 1, 1)
        self.lineEdit9 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit9.setFont(font)
        self.lineEdit9.setObjectName("lineEdit9")
        self.gridLayout_3.addWidget(self.lineEdit9, 0, 2, 1, 1)
        self.label21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label21.setFont(font)
        self.label21.setObjectName("label21")
        self.gridLayout_3.addWidget(self.label21, 14, 0, 1, 1)
        self.label38 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label38.setFont(font)
        self.label38.setObjectName("label38")
        self.gridLayout_3.addWidget(self.label38, 31, 0, 1, 1)
        self.label31 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label31.setFont(font)
        self.label31.setObjectName("label31")
        self.gridLayout_3.addWidget(self.label31, 24, 0, 1, 1)
        self.label15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label15.setFont(font)
        self.label15.setObjectName("label15")
        self.gridLayout_3.addWidget(self.label15, 8, 0, 1, 1)
        self.label37 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label37.setFont(font)
        self.label37.setObjectName("label37")
        self.gridLayout_3.addWidget(self.label37, 30, 0, 1, 1)
        self.label12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label12.setFont(font)
        self.label12.setObjectName("label12")
        self.gridLayout_3.addWidget(self.label12, 5, 0, 1, 1)
        self.label9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label9.setFont(font)
        self.label9.setObjectName("label9")
        self.gridLayout_3.addWidget(self.label9, 2, 0, 1, 1)
        self.label36 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label36.setFont(font)
        self.label36.setObjectName("label36")
        self.gridLayout_3.addWidget(self.label36, 29, 0, 1, 1)
        self.label14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label14.setFont(font)
        self.label14.setObjectName("label14")
        self.gridLayout_3.addWidget(self.label14, 7, 0, 1, 1)
        self.label_176 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_176.setFont(font)
        self.label_176.setObjectName("label_176")
        self.gridLayout_3.addWidget(self.label_176, 7, 1, 1, 1)
        self.label32 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label32.setFont(font)
        self.label32.setObjectName("label32")
        self.gridLayout_3.addWidget(self.label32, 25, 0, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.gridLayout_3.addWidget(self.label_62, 9, 1, 1, 1)
        self.label10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label10.setFont(font)
        self.label10.setObjectName("label10")
        self.gridLayout_3.addWidget(self.label10, 3, 0, 1, 1)
        self.label11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label11.setFont(font)
        self.label11.setObjectName("label11")
        self.gridLayout_3.addWidget(self.label11, 4, 0, 1, 1)
        self.label30 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label30.setFont(font)
        self.label30.setObjectName("label30")
        self.gridLayout_3.addWidget(self.label30, 23, 0, 1, 1)
        self.label13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label13.setFont(font)
        self.label13.setObjectName("label13")
        self.gridLayout_3.addWidget(self.label13, 6, 0, 1, 1)
        self.label17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label17.setFont(font)
        self.label17.setObjectName("label17")
        self.gridLayout_3.addWidget(self.label17, 10, 0, 1, 1)
        self.label18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label18.setFont(font)
        self.label18.setObjectName("label18")
        self.gridLayout_3.addWidget(self.label18, 11, 0, 1, 1)
        self.lineEdit33 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit33.setFont(font)
        self.lineEdit33.setObjectName("lineEdit33")
        self.gridLayout_3.addWidget(self.lineEdit33, 15, 4, 1, 1)
        self.lineEdit34 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit34.setFont(font)
        self.lineEdit34.setObjectName("lineEdit34")
        self.gridLayout_3.addWidget(self.lineEdit34, 16, 2, 1, 1)
        self.lineEdit37 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit37.setFont(font)
        self.lineEdit37.setObjectName("lineEdit37")
        self.gridLayout_3.addWidget(self.lineEdit37, 17, 4, 1, 1)
        self.lineEdit43 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit43.setFont(font)
        self.lineEdit43.setObjectName("lineEdit43")
        self.gridLayout_3.addWidget(self.lineEdit43, 20, 4, 1, 1)
        self.lineEdit47 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit47.setFont(font)
        self.lineEdit47.setObjectName("lineEdit47")
        self.gridLayout_3.addWidget(self.lineEdit47, 23, 2, 1, 1)
        self.lineEdit38 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit38.setFont(font)
        self.lineEdit38.setObjectName("lineEdit38")
        self.gridLayout_3.addWidget(self.lineEdit38, 18, 2, 1, 1)
        self.lineEdit49 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit49.setFont(font)
        self.lineEdit49.setObjectName("lineEdit49")
        self.gridLayout_3.addWidget(self.lineEdit49, 24, 2, 1, 1)
        self.lineEdit36 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit36.setFont(font)
        self.lineEdit36.setObjectName("lineEdit36")
        self.gridLayout_3.addWidget(self.lineEdit36, 17, 2, 1, 1)
        self.lineEdit50 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit50.setFont(font)
        self.lineEdit50.setObjectName("lineEdit50")
        self.gridLayout_3.addWidget(self.lineEdit50, 24, 4, 1, 1)
        self.lineEdit42 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit42.setFont(font)
        self.lineEdit42.setObjectName("lineEdit42")
        self.gridLayout_3.addWidget(self.lineEdit42, 20, 2, 1, 1)
        self.lineEdit45 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit45.setFont(font)
        self.lineEdit45.setObjectName("lineEdit45")
        self.gridLayout_3.addWidget(self.lineEdit45, 21, 4, 1, 1)
        self.lineEdit39 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit39.setFont(font)
        self.lineEdit39.setObjectName("lineEdit39")
        self.gridLayout_3.addWidget(self.lineEdit39, 18, 4, 1, 1)
        self.lineEdit48 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit48.setFont(font)
        self.lineEdit48.setObjectName("lineEdit48")
        self.gridLayout_3.addWidget(self.lineEdit48, 23, 4, 1, 1)
        self.lineEdit44 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit44.setFont(font)
        self.lineEdit44.setObjectName("lineEdit44")
        self.gridLayout_3.addWidget(self.lineEdit44, 21, 2, 1, 1)
        self.lineEdit35 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit35.setFont(font)
        self.lineEdit35.setObjectName("lineEdit35")
        self.gridLayout_3.addWidget(self.lineEdit35, 16, 4, 1, 1)
        self.lineEdit46 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit46.setFont(font)
        self.lineEdit46.setObjectName("lineEdit46")
        self.gridLayout_3.addWidget(self.lineEdit46, 22, 2, 1, 1)
        self.lineEdit52 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit52.setFont(font)
        self.lineEdit52.setObjectName("lineEdit52")
        self.gridLayout_3.addWidget(self.lineEdit52, 25, 4, 1, 1)
        self.lineEdit51 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit51.setFont(font)
        self.lineEdit51.setObjectName("lineEdit51")
        self.gridLayout_3.addWidget(self.lineEdit51, 25, 2, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.gridLayout_3.addWidget(self.label_60, 2, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.gridLayout_3.addWidget(self.label_56, 3, 3, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")
        self.gridLayout_3.addWidget(self.label_68, 11, 1, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_73.setFont(font)
        self.label_73.setObjectName("label_73")
        self.gridLayout_3.addWidget(self.label_73, 4, 3, 1, 1)
        self.label22 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label22.setFont(font)
        self.label22.setObjectName("label22")
        self.gridLayout_3.addWidget(self.label22, 15, 0, 1, 1)
        self.label24 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label24.setFont(font)
        self.label24.setObjectName("label24")
        self.gridLayout_3.addWidget(self.label24, 17, 0, 1, 1)
        self.label29 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label29.setFont(font)
        self.label29.setObjectName("label29")
        self.gridLayout_3.addWidget(self.label29, 22, 0, 1, 1)
        self.label35 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label35.setFont(font)
        self.label35.setObjectName("label35")
        self.gridLayout_3.addWidget(self.label35, 28, 0, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_82.setFont(font)
        self.label_82.setObjectName("label_82")
        self.gridLayout_3.addWidget(self.label_82, 0, 1, 1, 1)
        self.label19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label19.setFont(font)
        self.label19.setObjectName("label19")
        self.gridLayout_3.addWidget(self.label19, 12, 0, 1, 1)
        self.label7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label7.setFont(font)
        self.label7.setObjectName("label7")
        self.gridLayout_3.addWidget(self.label7, 0, 0, 1, 1)
        self.label16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label16.setFont(font)
        self.label16.setObjectName("label16")
        self.gridLayout_3.addWidget(self.label16, 9, 0, 1, 1)
        self.label34 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label34.setFont(font)
        self.label34.setObjectName("label34")
        self.gridLayout_3.addWidget(self.label34, 27, 0, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.gridLayout_3.addWidget(self.label_52, 16, 3, 1, 1)
        self.lineEdit15 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit15.setFont(font)
        self.lineEdit15.setObjectName("lineEdit15")
        self.gridLayout_3.addWidget(self.lineEdit15, 4, 2, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.gridLayout_3.addWidget(self.label_51, 17, 3, 1, 1)
        self.label_180 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_180.setFont(font)
        self.label_180.setObjectName("label_180")
        self.gridLayout_3.addWidget(self.label_180, 18, 3, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_75.setFont(font)
        self.label_75.setObjectName("label_75")
        self.gridLayout_3.addWidget(self.label_75, 18, 1, 1, 1)
        self.lineEdit13 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit13.setFont(font)
        self.lineEdit13.setObjectName("lineEdit13")
        self.gridLayout_3.addWidget(self.lineEdit13, 3, 2, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_74.setFont(font)
        self.label_74.setObjectName("label_74")
        self.gridLayout_3.addWidget(self.label_74, 17, 1, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_84.setFont(font)
        self.label_84.setObjectName("label_84")
        self.gridLayout_3.addWidget(self.label_84, 8, 3, 1, 1)
        self.label33 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label33.setFont(font)
        self.label33.setObjectName("label33")
        self.gridLayout_3.addWidget(self.label33, 26, 0, 1, 1)
        self.label8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label8.setFont(font)
        self.label8.setObjectName("label8")
        self.gridLayout_3.addWidget(self.label8, 1, 0, 1, 1)
        self.lineEdit10 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit10.setFont(font)
        self.lineEdit10.setObjectName("lineEdit10")
        self.gridLayout_3.addWidget(self.lineEdit10, 1, 2, 1, 1)
        self.label28 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label28.setFont(font)
        self.label28.setObjectName("label28")
        self.gridLayout_3.addWidget(self.label28, 21, 0, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_83.setFont(font)
        self.label_83.setObjectName("label_83")
        self.gridLayout_3.addWidget(self.label_83, 1, 1, 1, 1)
        self.label20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label20.setFont(font)
        self.label20.setObjectName("label20")
        self.gridLayout_3.addWidget(self.label20, 13, 0, 1, 1)
        self.label27 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label27.setFont(font)
        self.label27.setObjectName("label27")
        self.gridLayout_3.addWidget(self.label27, 20, 0, 1, 1)
        self.label_177 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_177.setFont(font)
        self.label_177.setObjectName("label_177")
        self.gridLayout_3.addWidget(self.label_177, 8, 1, 1, 1)
        self.label25 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label25.setFont(font)
        self.label25.setObjectName("label25")
        self.gridLayout_3.addWidget(self.label25, 18, 0, 1, 1)
        self.label_185 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_185.setFont(font)
        self.label_185.setObjectName("label_185")
        self.gridLayout_3.addWidget(self.label_185, 27, 1, 1, 1)
        self.lineEdit30 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit30.setFont(font)
        self.lineEdit30.setObjectName("lineEdit30")
        self.gridLayout_3.addWidget(self.lineEdit30, 13, 2, 1, 1)
        self.lineEdit32 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit32.setFont(font)
        self.lineEdit32.setObjectName("lineEdit32")
        self.gridLayout_3.addWidget(self.lineEdit32, 15, 2, 1, 1)
        self.lineEdit27 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit27.setFont(font)
        self.lineEdit27.setObjectName("lineEdit27")
        self.gridLayout_3.addWidget(self.lineEdit27, 11, 2, 1, 1)
        self.lineEdit24 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit24.setFont(font)
        self.lineEdit24.setObjectName("lineEdit24")
        self.gridLayout_3.addWidget(self.lineEdit24, 9, 4, 1, 1)
        self.lineEdit31 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit31.setFont(font)
        self.lineEdit31.setObjectName("lineEdit31")
        self.gridLayout_3.addWidget(self.lineEdit31, 14, 2, 1, 1)
        self.lineEdit22 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit22.setFont(font)
        self.lineEdit22.setObjectName("lineEdit22")
        self.gridLayout_3.addWidget(self.lineEdit22, 8, 4, 1, 1)
        self.lineEdit23 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit23.setFont(font)
        self.lineEdit23.setObjectName("lineEdit23")
        self.gridLayout_3.addWidget(self.lineEdit23, 9, 2, 1, 1)
        self.lineEdit28 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit28.setFont(font)
        self.lineEdit28.setObjectName("lineEdit28")
        self.gridLayout_3.addWidget(self.lineEdit28, 11, 4, 1, 1)
        self.lineEdit26 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit26.setFont(font)
        self.lineEdit26.setObjectName("lineEdit26")
        self.gridLayout_3.addWidget(self.lineEdit26, 10, 4, 1, 1)
        self.lineEdit29 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit29.setFont(font)
        self.lineEdit29.setObjectName("lineEdit29")
        self.gridLayout_3.addWidget(self.lineEdit29, 12, 2, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.gridLayout_3.addWidget(self.label_65, 26, 1, 1, 1)
        self.lineEdit25 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit25.setFont(font)
        self.lineEdit25.setObjectName("lineEdit25")
        self.gridLayout_3.addWidget(self.lineEdit25, 10, 2, 1, 1)
        self.label_186 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_186.setFont(font)
        self.label_186.setObjectName("label_186")
        self.gridLayout_3.addWidget(self.label_186, 26, 3, 1, 1)
        self.label_85 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_85.setFont(font)
        self.label_85.setObjectName("label_85")
        self.gridLayout_3.addWidget(self.label_85, 25, 3, 1, 1)
        self.label_179 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_179.setFont(font)
        self.label_179.setObjectName("label_179")
        self.gridLayout_3.addWidget(self.label_179, 10, 3, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.gridLayout_3.addWidget(self.label_50, 9, 3, 1, 1)
        self.label26 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label26.setFont(font)
        self.label26.setObjectName("label26")
        self.gridLayout_3.addWidget(self.label26, 19, 0, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.gridLayout_3.addWidget(self.label_61, 19, 1, 1, 1)
        self.label_86 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_86.setFont(font)
        self.label_86.setObjectName("label_86")
        self.gridLayout_3.addWidget(self.label_86, 19, 3, 1, 1)
        self.lineEdit40 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit40.setFont(font)
        self.lineEdit40.setObjectName("lineEdit40")
        self.gridLayout_3.addWidget(self.lineEdit40, 19, 2, 1, 1)
        self.lineEdit41 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit41.setFont(font)
        self.lineEdit41.setObjectName("lineEdit41")
        self.gridLayout_3.addWidget(self.lineEdit41, 19, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem6)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_6.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE)
        QtCore.QMetaObject.connectSlotsByName(ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE)

    def retranslateUi(self, ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE):
        _translate = QtCore.QCoreApplication.translate
        ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE.setWindowTitle(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "ENGRENAGE CONIQUE DROIT DENTURE NORMALE"))
        self.label_2.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Valeurs d\'entrée"))
        self.label_30.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Z1"))
        self.label5.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Nombre de dent"))
        self.label_154.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Σ"))
        self.label_27.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "∝"))
        self.label1.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Module normalisé"))
        self.label2.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Angle de pression reél"))
        self.label3.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Angle de croisement"))
        self.label_46.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Z2"))
        self.label_25.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "m"))
        self.label4.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "La largeur de dent"))
        self.label_170.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "b"))
        self.pushButton.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "CALCULEZ"))
        self.pushButton_3.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "SAUVEGARDER LES RESULTATS DU CALCUL"))
        self.label_45.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Valeurs de sortie"))
        self.label_175.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "δ2"))
        self.label_41.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "hf1"))
        self.label_174.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "δ1"))
        self.label_63.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "h"))
        self.label_53.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "ha1"))
        self.label_55.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "SC1"))
        self.label_67.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Rm"))
        self.label_49.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "s2"))
        self.label_72.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "s1"))
        self.label_59.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Ri"))
        self.label_69.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "d2"))
        self.label_184.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "gav2"))
        self.label_182.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "gav1"))
        self.label_81.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "gv"))
        self.label_183.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "dbv1"))
        self.label_71.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "mn"))
        self.label_70.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "δf2"))
        self.label_178.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "δa1"))
        self.label_54.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "zv2"))
        self.label_181.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "dai1"))
        self.label_44.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "dai2"))
        self.label_77.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "av"))
        self.label_80.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "εv2"))
        self.label_79.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "dfv2"))
        self.label_66.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "εv"))
        self.label_64.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "εv1"))
        self.label_76.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "dv1"))
        self.label_78.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "dav2"))
        self.label_58.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "dav1"))
        self.label_57.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "dfv1"))
        self.label_43.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "dv2"))
        self.label23.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Epaisseur de la dent à la corde "))
        self.label21.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Module moyen"))
        self.label38.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Longueur de conduite totale"))
        self.label31.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Diamètre virtuel de pied"))
        self.label15.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Angle de Saillie"))
        self.label37.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Longueur de conduite partielle"))
        self.label12.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Hauteur de la dent"))
        self.label9.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Diamètre primitif"))
        self.label36.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Rapport de conduite totale"))
        self.label14.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Génératrice primitive"))
        self.label_176.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "R"))
        self.label32.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Diamètre virtuel de base"))
        self.label_62.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "θf1"))
        self.label10.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Saillie"))
        self.label11.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Creux"))
        self.label30.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Diamètre virtuel de tête"))
        self.label13.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Angle primitif"))
        self.label17.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Angle de tête"))
        self.label18.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Angle de pied"))
        self.label_60.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "d1"))
        self.label_56.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "ha2"))
        self.label_68.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "δf1"))
        self.label_73.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "hf2"))
        self.label22.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Epaisseur de la dent"))
        self.label24.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Hauteur de mesure de la tête de dent"))
        self.label29.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Entraxe"))
        self.label35.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Rapport de conduite partiel"))
        self.label_82.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "U"))
        self.label19.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Génératrice moyenne"))
        self.label7.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Le rapport d\'engrenage"))
        self.label16.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Angle de creux"))
        self.label34.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Nombre de dents virtuel"))
        self.label_52.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "SC2"))
        self.label_51.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "ham2"))
        self.label_180.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "da2"))
        self.label_75.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "da1"))
        self.label_74.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "ham1"))
        self.label_84.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "θa2"))
        self.label33.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Angle de pression virtuel de tête"))
        self.label8.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Le rapport de transmission"))
        self.label28.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Diamètre virtuel primitif"))
        self.label_83.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "i"))
        self.label20.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Génératrice intérieure"))
        self.label27.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Diamètre de tête intérieure"))
        self.label_177.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "θa1"))
        self.label25.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Diamètre de tête"))
        self.label_185.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "zv1"))
        self.label_65.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "∝av1"))
        self.label_186.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "∝av2"))
        self.label_85.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "dbv2"))
        self.label_179.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "δa2"))
        self.label_50.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "θf2"))
        self.label26.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "Diamètre de pied"))
        self.label_61.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "df1"))
        self.label_86.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "df2"))
        self.pushButton_2.setText(_translate("ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE", "RETOUR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE = QtWidgets.QWidget()
    ui = Ui_ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE()
    ui.setupUi(ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE)
    ENGRENAGE_CONIQUE_DROIT_DENTURE_NORMALE.show()
    sys.exit(app.exec_())
