
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import openpyxl
import math


class Ui_DENTURE_DROITE_PARALLELE(object):


    def calculer_engrenage(self):
        try:

            m = float(self.lineEdit1.text())
            alpha = float(self.lineEdit2.text())
            P = float(self.lineEdit3.text())
            N = float(self.lineEdit4.text())
            Zm = float(self.lineEdit5.text())    
            η = float(self.lineEdit6.text())

            C1 = (30*P)/(math.pi*N)
            FT1 = ((2*C1)/(m*Zm))*1000
            FR1 = FT1*math.tan(math.radians(alpha))
            F1 = FT1/math.cos(math.radians(alpha))

            C2 = η*C1
            FT2 = η*FT1
            FR2 = η*FR1
            F2 = η*F1

        except ValueError:
            QMessageBox.warning(None, "Erreur de saisie", "Il est impossible d'effectuer le calcul. Vérifiez les valeurs d'entrée.")
            return
        except ZeroDivisionError:
            QMessageBox.warning(None, "Erreur de saisie", "Il est impossible d'effectuer le calcul. Vérifiez les valeurs d'entrée.")
            return

        # Affichage des resultats dans les LineEdit
        self.lineEdit7.setText(str(C1))
        self.lineEdit8.setText(str(FT1))
        self.lineEdit9.setText(str(FR1))
        self.lineEdit10.setText(str(F1))
        self.lineEdit11.setText(str(C2))
        self.lineEdit12.setText(str(FT2))
        self.lineEdit13.setText(str(FR2))
        self.lineEdit14.setText(str(F2))
        

    def sauvegarder_dans_excel(self):
        wb = openpyxl.Workbook()
        ws = wb.active

        noms_labels = [
            self.label1.text(),
            self.label2.text(),
            self.label3.text(),
            self.label4.text(),
            self.label5.text(),
            self.label6.text(),
            self.label7.text(),
            self.label8.text(),
            self.label9.text(),
            self.label10.text(),
            self.label11.text(),
            self.label12.text(),
            self.label13.text(),
            self.label14.text(),
            
        ]

        symboles = [
            'mn', '∝', 'P', 'N', 'Z', 'η', 'C1', 'FT1', 'FR1', 'F1', 'C2', 'FT2', 'FR2', 'F2'
        ]

        valeurs = [

            self.lineEdit1.text(),
            self.lineEdit2.text(),
            self.lineEdit3.text(),
            self.lineEdit4.text(),   
            self.lineEdit5.text(),
            self.lineEdit6.text(),
            self.lineEdit7.text(),
            self.lineEdit8.text(),
            self.lineEdit9.text(),
            self.lineEdit10.text(),
            self.lineEdit11.text(),
            self.lineEdit12.text(),
            self.lineEdit13.text(),
            self.lineEdit14.text(),
   
        ]

        unites = [

            'mm', 'degré', 'W', 'tr/mn', '', '%', 'N.m', 'N', 'N', 'N', 'N.m', 'N', 'N', 'N'
        ]

        entete = ['Nom(s)', 'Symbole(s)', 'Valeur(s)', 'Unité(s)']
        ws.append(entete)

        for i in range(len(noms_labels)):
            ws.append([noms_labels[i], symboles[i], valeurs[i], unites[i]])

        for row in ws.iter_rows(min_row=1, max_row=15, min_col=1, max_col=4):
            for cell in row:
                cell.border = openpyxl.styles.Border(
                    left=openpyxl.styles.Side(border_style='thin'),
                    right=openpyxl.styles.Side(border_style='thin'),
                    top=openpyxl.styles.Side(border_style='thin'),
                    bottom=openpyxl.styles.Side(border_style='thin')
                )

        for row in ws.iter_rows(min_row=1, max_row=1, min_col=1, max_col=4):
            for cell in row:
                cell.fill = openpyxl.styles.PatternFill(start_color="0070C0", end_color="0070C0", fill_type="solid")
                cell.font = openpyxl.styles.Font(color="FFFFFF", bold=True)


        file_path, _ = QtWidgets.QFileDialog.getSaveFileName(None, "Enregistrer le fichier Excel", "", "Excel Files (*.xlsx)")
        if file_path:
            wb.save(file_path)
            QtWidgets.QMessageBox.information(None, "Enregistrement", "Fichier Excel enregistré avec succès !")




    def setupUi(self, DENTURE_DROITE_PARALLELE):
        DENTURE_DROITE_PARALLELE.setObjectName("DENTURE_DROITE_PARALLELE")
        DENTURE_DROITE_PARALLELE.setWindowModality(QtCore.Qt.WindowModal)
        DENTURE_DROITE_PARALLELE.resize(550, 372)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../.designer/backup/reducteur_gearexpert.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DENTURE_DROITE_PARALLELE.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(DENTURE_DROITE_PARALLELE)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(DENTURE_DROITE_PARALLELE)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 523, 812))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 4, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label5.setFont(font)
        self.label5.setObjectName("label5")
        self.gridLayout_2.addWidget(self.label5, 4, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.label_154 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_154.setFont(font)
        self.label_154.setObjectName("label_154")
        self.gridLayout_2.addWidget(self.label_154, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.gridLayout_2.addWidget(self.label1, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.label2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.gridLayout_2.addWidget(self.label2, 1, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.lineEdit1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit1.setFont(font)
        self.lineEdit1.setObjectName("lineEdit1")
        self.gridLayout_2.addWidget(self.lineEdit1, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.gridLayout_2.addWidget(self.label3, 2, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.lineEdit2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit2.setFont(font)
        self.lineEdit2.setObjectName("lineEdit2")
        self.gridLayout_2.addWidget(self.lineEdit2, 1, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit5.setFont(font)
        self.lineEdit5.setObjectName("lineEdit5")
        self.gridLayout_2.addWidget(self.lineEdit5, 4, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label4.setFont(font)
        self.label4.setObjectName("label4")
        self.gridLayout_2.addWidget(self.label4, 3, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.lineEdit4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit4.setFont(font)
        self.lineEdit4.setObjectName("lineEdit4")
        self.gridLayout_2.addWidget(self.lineEdit4, 3, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit3.setFont(font)
        self.lineEdit3.setObjectName("lineEdit3")
        self.gridLayout_2.addWidget(self.lineEdit3, 2, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_170 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_170.setFont(font)
        self.label_170.setObjectName("label_170")
        self.gridLayout_2.addWidget(self.label_170, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label6.setFont(font)
        self.label6.setObjectName("label6")
        self.gridLayout_2.addWidget(self.label6, 5, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.label_49 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.gridLayout_2.addWidget(self.label_49, 5, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit6.setFont(font)
        self.lineEdit6.setObjectName("lineEdit6")
        self.gridLayout_2.addWidget(self.lineEdit6, 5, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setMaximumSize(QtCore.QSize(180, 180))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.calculer_engrenage) # Liaison du clic du bouton à la fonction de calcul
        ############################################################################################################

        self.verticalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")

        self.pushButton_3.clicked.connect(self.sauvegarder_dans_excel)  # Connecte le clic du bouton à la fonction de sauvegarde
        #######################################################################################################################

        self.verticalLayout.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        self.label_45 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.verticalLayout.addWidget(self.label_45, 0, QtCore.Qt.AlignHCenter)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem4)
        self.label_46 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.verticalLayout.addWidget(self.label_46, 0, QtCore.Qt.AlignHCenter)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem5)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_53 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.gridLayout_3.addWidget(self.label_53, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit9 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit9.setFont(font)
        self.lineEdit9.setObjectName("lineEdit9")
        self.gridLayout_3.addWidget(self.lineEdit9, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit7.setFont(font)
        self.lineEdit7.setObjectName("lineEdit7")
        self.gridLayout_3.addWidget(self.lineEdit7, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label9.setFont(font)
        self.label9.setObjectName("label9")
        self.gridLayout_3.addWidget(self.label9, 2, 0, 1, 1)
        self.label10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label10.setFont(font)
        self.label10.setObjectName("label10")
        self.gridLayout_3.addWidget(self.label10, 3, 0, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.gridLayout_3.addWidget(self.label_60, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_82 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_82.setFont(font)
        self.label_82.setObjectName("label_82")
        self.gridLayout_3.addWidget(self.label_82, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit10 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit10.setFont(font)
        self.lineEdit10.setObjectName("lineEdit10")
        self.gridLayout_3.addWidget(self.lineEdit10, 3, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label7.setFont(font)
        self.label7.setObjectName("label7")
        self.gridLayout_3.addWidget(self.label7, 0, 0, 1, 1)
        self.lineEdit8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit8.setFont(font)
        self.lineEdit8.setObjectName("lineEdit8")
        self.gridLayout_3.addWidget(self.lineEdit8, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_83 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_83.setFont(font)
        self.label_83.setObjectName("label_83")
        self.gridLayout_3.addWidget(self.label_83, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label8.setFont(font)
        self.label8.setObjectName("label8")
        self.gridLayout_3.addWidget(self.label8, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem6)
        self.label_50 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.verticalLayout.addWidget(self.label_50, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_55 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.gridLayout_5.addWidget(self.label_55, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit13 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit13.setFont(font)
        self.lineEdit13.setObjectName("lineEdit13")
        self.gridLayout_5.addWidget(self.lineEdit13, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit11 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit11.setFont(font)
        self.lineEdit11.setObjectName("lineEdit11")
        self.gridLayout_5.addWidget(self.lineEdit11, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label13.setFont(font)
        self.label13.setObjectName("label13")
        self.gridLayout_5.addWidget(self.label13, 2, 0, 1, 1)
        self.label14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label14.setFont(font)
        self.label14.setObjectName("label14")
        self.gridLayout_5.addWidget(self.label14, 3, 0, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.gridLayout_5.addWidget(self.label_62, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_86 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_86.setFont(font)
        self.label_86.setObjectName("label_86")
        self.gridLayout_5.addWidget(self.label_86, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit14 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit14.setFont(font)
        self.lineEdit14.setObjectName("lineEdit14")
        self.gridLayout_5.addWidget(self.lineEdit14, 3, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label11.setFont(font)
        self.label11.setObjectName("label11")
        self.gridLayout_5.addWidget(self.label11, 0, 0, 1, 1)
        self.lineEdit12 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit12.setFont(font)
        self.lineEdit12.setObjectName("lineEdit12")
        self.gridLayout_5.addWidget(self.lineEdit12, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_87 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_87.setFont(font)
        self.label_87.setObjectName("label_87")
        self.gridLayout_5.addWidget(self.label_87, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label12.setFont(font)
        self.label12.setObjectName("label12")
        self.gridLayout_5.addWidget(self.label12, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem8)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_6.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(DENTURE_DROITE_PARALLELE)
        QtCore.QMetaObject.connectSlotsByName(DENTURE_DROITE_PARALLELE)

    def retranslateUi(self, DENTURE_DROITE_PARALLELE):
        _translate = QtCore.QCoreApplication.translate
        DENTURE_DROITE_PARALLELE.setWindowTitle(_translate("DENTURE_DROITE_PARALLELE", "DENTURE_DROITE_PARALLELE"))
        self.label_2.setText(_translate("DENTURE_DROITE_PARALLELE", "Valeurs d\'entrée"))
        self.label_30.setText(_translate("DENTURE_DROITE_PARALLELE", "Z"))
        self.label5.setText(_translate("DENTURE_DROITE_PARALLELE", "Nombre de dent pour la roue menant"))
        self.label_154.setText(_translate("DENTURE_DROITE_PARALLELE", "P"))
        self.label_27.setText(_translate("DENTURE_DROITE_PARALLELE", "∝"))
        self.label1.setText(_translate("DENTURE_DROITE_PARALLELE", "Module normalisé"))
        self.label2.setText(_translate("DENTURE_DROITE_PARALLELE", "Angle de pression reél"))
        self.label3.setText(_translate("DENTURE_DROITE_PARALLELE", "Puissance"))
        self.label_25.setText(_translate("DENTURE_DROITE_PARALLELE", "m"))
        self.label4.setText(_translate("DENTURE_DROITE_PARALLELE", "Nombre de tr/min"))
        self.label_170.setText(_translate("DENTURE_DROITE_PARALLELE", "N"))
        self.label6.setText(_translate("DENTURE_DROITE_PARALLELE", "Rendement"))
        self.label_49.setText(_translate("DENTURE_DROITE_PARALLELE", "η"))
        self.pushButton.setText(_translate("DENTURE_DROITE_PARALLELE", "CALCULEZ"))
        self.pushButton_3.setText(_translate("DENTURE_DROITE_PARALLELE", "SAUVEGARDEZ LES RESULTATS DU CALCUL"))
        self.label_45.setText(_translate("DENTURE_DROITE_PARALLELE", "Valeurs de sortie"))
        self.label_46.setText(_translate("DENTURE_DROITE_PARALLELE", "Roue menant"))
        self.label_53.setText(_translate("DENTURE_DROITE_PARALLELE", "F1"))
        self.label9.setText(_translate("DENTURE_DROITE_PARALLELE", "Effort radial"))
        self.label10.setText(_translate("DENTURE_DROITE_PARALLELE", "Effort sur la dent"))
        self.label_60.setText(_translate("DENTURE_DROITE_PARALLELE", "FR1"))
        self.label_82.setText(_translate("DENTURE_DROITE_PARALLELE", "C1"))
        self.label7.setText(_translate("DENTURE_DROITE_PARALLELE", "Couple"))
        self.label_83.setText(_translate("DENTURE_DROITE_PARALLELE", "FT1"))
        self.label8.setText(_translate("DENTURE_DROITE_PARALLELE", "Effort tangentiel"))
        self.label_50.setText(_translate("DENTURE_DROITE_PARALLELE", "Roue meneé"))
        self.label_55.setText(_translate("DENTURE_DROITE_PARALLELE", "F2"))
        self.label13.setText(_translate("DENTURE_DROITE_PARALLELE", "Effort radial"))
        self.label14.setText(_translate("DENTURE_DROITE_PARALLELE", "Effort sur la dent"))
        self.label_62.setText(_translate("DENTURE_DROITE_PARALLELE", "FR2"))
        self.label_86.setText(_translate("DENTURE_DROITE_PARALLELE", "C2"))
        self.label11.setText(_translate("DENTURE_DROITE_PARALLELE", "Couple"))
        self.label_87.setText(_translate("DENTURE_DROITE_PARALLELE", "FT2"))
        self.label12.setText(_translate("DENTURE_DROITE_PARALLELE", "Effort tangentiel"))
        self.pushButton_2.setText(_translate("DENTURE_DROITE_PARALLELE", "RETOUR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DENTURE_DROITE_PARALLELE = QtWidgets.QWidget()
    ui = Ui_DENTURE_DROITE_PARALLELE()
    ui.setupUi(DENTURE_DROITE_PARALLELE)
    DENTURE_DROITE_PARALLELE.show()
    sys.exit(app.exec_())
