
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import openpyxl
import math 


class Ui_ROUE_VIS_SANS_FIN(object):


    def calculer_engrenage(self):
        try:

            mn = float(self.lineEdit1.text())
            alpha = float(self.lineEdit2.text())
            q = float(self.lineEdit3.text())
            zr = float(self.lineEdit4.text())
            zv = float(self.lineEdit5.text())    
            μ = float(self.lineEdit5_1.text())

            beta_v1 = math.atan(zv / q)
            beta_v = math.degrees(beta_v1)
            beta_r = 90 - beta_v

            dv = mn * q
            mx = mn / math.cos(math.radians(beta_r))
            pn = math.pi * mn
            pt = pn / math.cos(math.radians(beta_r))
            mt = pt/math.pi
            px = pt
            pz = zv*px
            dr = mt * zr
            dv = pz / (math.pi * math.tan(math.radians(beta_r)))
            a = (dv + dr) / 2
            ha = mn
            hf = 1.25 * mn
            h = ha + hf
            dav = dv + 2 * mn
            dfv = dv - 2.5 * mn
            alpha_t1 = math.atan(math.tan(math.radians(alpha)) / math.cos(math.radians(beta_r)))
            alpha_t = math.degrees(alpha_t1)
            L = 5*px
            b = 2 * mn * (0.5 + (1 + (zv / (math.tan(math.radians(beta_r)))))**(1/2))
            alpha_x = alpha_t
            r1 = (1-(μ*math.tan(math.radians(beta_v))))/(1+(μ*math.tan(math.radians(beta_v))))
            r = 100*r1

        except ValueError:
            QMessageBox.warning(None, "Erreur de saisie", "Il est impossible d'effectuer le calcul. Vérifiez les valeurs d'entrée.")
            return
        except ZeroDivisionError:
            QMessageBox.warning(None, "Erreur de saisie", "Il est impossible d'effectuer le calcul. Vérifiez les valeurs d'entrée.")
            return

        # Affichage des resultats dans les LineEdit
        self.lineEdit6.setText(str(beta_v))
        self.lineEdit7.setText(str(beta_r))
        self.lineEdit8.setText(str(mx))
        self.lineEdit9.setText(str(pn))
        self.lineEdit10.setText(str(pt))
        self.lineEdit11.setText(str(px))
        self.lineEdit12.setText(str(pz))
        self.lineEdit13.setText(str(dr))
        self.lineEdit14.setText(str(dv))
        self.lineEdit15.setText(str(a))
        self.lineEdit16.setText(str(ha))
        self.lineEdit17.setText(str(hf))
        self.lineEdit18.setText(str(h))
        self.lineEdit19.setText(str(dav))
        self.lineEdit20.setText(str(dfv))
        self.lineEdit21.setText(str(alpha_x))
        self.lineEdit22.setText(str(L))
        self.lineEdit23.setText(str(b))
        self.lineEdit24.setText(str(r))
        

    def sauvegarder_dans_excel(self):
        wb = openpyxl.Workbook()
        ws = wb.active

        noms_labels = [
            self.label1.text(),
            self.label2.text(),
            self.label3.text(),
            self.label4.text(),
            self.label5.text(),
            self.label6.text(),
            self.label7.text(),
            self.label8.text(),
            self.label9.text(),
            self.label10.text(),
            self.label11.text(),
            self.label12.text(),
            self.label13.text(),
            self.label14.text(),
            self.label15.text(),
            self.label16.text(),
            self.label17.text(),
            self.label18.text(),
            self.label19.text(),
            self.label20.text(),
            self.label21.text(),
            self.label22.text(),
            self.label23.text(),
            self.label24.text(),
            self.label_8.text(),
            
        ]

        symboles = [
            'm', '∝', 'q', 'zr', 'zv', 'μ', 'βv', 'βr', 'mx', 'pn',
            'pt', 'px', 'pz', 'dr' , 'dv', 'a', 'ha','hf', 'h', 'dav',
            'dfv', '∝x', 'L', 'b', 'η'
            
        ]


        valeurs = [

            self.lineEdit1.text(),
            self.lineEdit2.text(),
            self.lineEdit3.text(),
            self.lineEdit4.text(),   
            self.lineEdit5.text(),
            self.lineEdit5_1.text(),
            self.lineEdit6.text(),
            self.lineEdit7.text(),
            self.lineEdit8.text(),
            self.lineEdit9.text(),
            self.lineEdit10.text(),
            self.lineEdit11.text(),
            self.lineEdit12.text(),
            self.lineEdit13.text(),
            self.lineEdit14.text(),
            self.lineEdit15.text(),
            self.lineEdit16.text(),
            self.lineEdit17.text(),
            self.lineEdit18.text(),
            self.lineEdit19.text(),
            self.lineEdit20.text(),
            self.lineEdit21.text(),
            self.lineEdit22.text(),
            self.lineEdit23.text(),
            self.lineEdit24.text(),
    

            
        ]

        unites = [

            'mm', 'degré', '', '', '', '', 'degré', 'degré', 'mm', 'mm',
            'mm', 'mm', 'mm', 'mm' , 'mm', 'mm', 'mm','mm', 'mm', 'mm',
            'mm', 'degré', 'mm', 'mm', '%'

        ]

        entete = ['Nom(s)', 'Symbole(s)', 'Valeur(s)', 'Unité(s)']
        ws.append(entete)

        for i in range(len(noms_labels)):
            ws.append([noms_labels[i], symboles[i], valeurs[i], unites[i]])

        for row in ws.iter_rows(min_row=1, max_row=26, min_col=1, max_col=4):
            for cell in row:
                cell.border = openpyxl.styles.Border(
                    left=openpyxl.styles.Side(border_style='thin'),
                    right=openpyxl.styles.Side(border_style='thin'),
                    top=openpyxl.styles.Side(border_style='thin'),
                    bottom=openpyxl.styles.Side(border_style='thin')
                )

        for row in ws.iter_rows(min_row=1, max_row=1, min_col=1, max_col=4):
            for cell in row:
                cell.fill = openpyxl.styles.PatternFill(start_color="0070C0", end_color="0070C0", fill_type="solid")
                cell.font = openpyxl.styles.Font(color="FFFFFF", bold=True)


        file_path, _ = QtWidgets.QFileDialog.getSaveFileName(None, "Enregistrer le fichier Excel", "", "Excel Files (*.xlsx)")
        if file_path:
            wb.save(file_path)
            QtWidgets.QMessageBox.information(None, "Enregistrement", "Fichier Excel enregistré avec succès !")


    def setupUi(self, ROUE_VIS_SANS_FIN):
        ROUE_VIS_SANS_FIN.setObjectName("ROUE_VIS_SANS_FIN")
        ROUE_VIS_SANS_FIN.resize(550, 372)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("reducteur_gearexpert.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ROUE_VIS_SANS_FIN.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(ROUE_VIS_SANS_FIN)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(ROUE_VIS_SANS_FIN)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -35, 523, 1050))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 4, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label5.setFont(font)
        self.label5.setObjectName("label5")
        self.gridLayout_2.addWidget(self.label5, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_154 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_154.setFont(font)
        self.label_154.setObjectName("label_154")
        self.gridLayout_2.addWidget(self.label_154, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.gridLayout_2.addWidget(self.label1, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.gridLayout_2.addWidget(self.label2, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit1.setFont(font)
        self.lineEdit1.setObjectName("lineEdit1")
        self.gridLayout_2.addWidget(self.lineEdit1, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.gridLayout_2.addWidget(self.label3, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit2.setFont(font)
        self.lineEdit2.setObjectName("lineEdit2")
        self.gridLayout_2.addWidget(self.lineEdit2, 1, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit5.setFont(font)
        self.lineEdit5.setObjectName("lineEdit5")
        self.gridLayout_2.addWidget(self.lineEdit5, 4, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label4.setFont(font)
        self.label4.setObjectName("label4")
        self.gridLayout_2.addWidget(self.label4, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit4.setFont(font)
        self.lineEdit4.setObjectName("lineEdit4")
        self.gridLayout_2.addWidget(self.lineEdit4, 3, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit3.setFont(font)
        self.lineEdit3.setObjectName("lineEdit3")
        self.gridLayout_2.addWidget(self.lineEdit3, 2, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_170 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_170.setFont(font)
        self.label_170.setObjectName("label_170")
        self.gridLayout_2.addWidget(self.label_170, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label6.setFont(font)
        self.label6.setObjectName("label6")
        self.gridLayout_2.addWidget(self.label6, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_49 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.gridLayout_2.addWidget(self.label_49, 5, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit5_1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit5_1.setFont(font)
        self.lineEdit5_1.setObjectName("lineEdit5_1")
        self.gridLayout_2.addWidget(self.lineEdit5_1, 5, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setMaximumSize(QtCore.QSize(180, 180))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.calculer_engrenage) # Liaison du clic du bouton à la fonction de calcul
        #############################################################################################################

        self.verticalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")

        self.pushButton_3.clicked.connect(self.sauvegarder_dans_excel)  # Connecte le clic du bouton à la fonction de sauvegarde
        ########################################################################################################################

        self.verticalLayout.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        self.label_45 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.verticalLayout.addWidget(self.label_45, 0, QtCore.Qt.AlignHCenter)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem4)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_41 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.gridLayout_3.addWidget(self.label_41, 4, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_174 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_174.setFont(font)
        self.label_174.setObjectName("label_174")
        self.gridLayout_3.addWidget(self.label_174, 6, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_63 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.gridLayout_3.addWidget(self.label_63, 5, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_53 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.gridLayout_3.addWidget(self.label_53, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_55 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.gridLayout_3.addWidget(self.label_55, 16, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_67 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.gridLayout_3.addWidget(self.label_67, 12, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_72 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_72.setFont(font)
        self.label_72.setObjectName("label_72")
        self.gridLayout_3.addWidget(self.label_72, 15, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_59 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.gridLayout_3.addWidget(self.label_59, 13, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_71 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_71.setFont(font)
        self.label_71.setObjectName("label_71")
        self.gridLayout_3.addWidget(self.label_71, 14, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit13 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit13.setFont(font)
        self.lineEdit13.setObjectName("lineEdit13")
        self.gridLayout_3.addWidget(self.lineEdit13, 7, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit14 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit14.setFont(font)
        self.lineEdit14.setObjectName("lineEdit14")
        self.gridLayout_3.addWidget(self.lineEdit14, 8, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit12 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit12.setFont(font)
        self.lineEdit12.setObjectName("lineEdit12")
        self.gridLayout_3.addWidget(self.lineEdit12, 6, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit11 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit11.setFont(font)
        self.lineEdit11.setObjectName("lineEdit11")
        self.gridLayout_3.addWidget(self.lineEdit11, 5, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_178 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_178.setFont(font)
        self.label_178.setObjectName("label_178")
        self.gridLayout_3.addWidget(self.label_178, 10, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit8.setFont(font)
        self.lineEdit8.setObjectName("lineEdit8")
        self.gridLayout_3.addWidget(self.lineEdit8, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label23 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label23.setFont(font)
        self.label23.setObjectName("label23")
        self.gridLayout_3.addWidget(self.label23, 16, 0, 1, 1)
        self.lineEdit6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit6.setFont(font)
        self.lineEdit6.setObjectName("lineEdit6")
        self.gridLayout_3.addWidget(self.lineEdit6, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label21.setFont(font)
        self.label21.setObjectName("label21")
        self.gridLayout_3.addWidget(self.label21, 14, 0, 1, 1)
        self.label15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label15.setFont(font)
        self.label15.setObjectName("label15")
        self.gridLayout_3.addWidget(self.label15, 8, 0, 1, 1)
        self.label12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label12.setFont(font)
        self.label12.setObjectName("label12")
        self.gridLayout_3.addWidget(self.label12, 5, 0, 1, 1)
        self.label9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label9.setFont(font)
        self.label9.setObjectName("label9")
        self.gridLayout_3.addWidget(self.label9, 2, 0, 1, 1)
        self.label14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label14.setFont(font)
        self.label14.setObjectName("label14")
        self.gridLayout_3.addWidget(self.label14, 7, 0, 1, 1)
        self.label_176 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_176.setFont(font)
        self.label_176.setObjectName("label_176")
        self.gridLayout_3.addWidget(self.label_176, 7, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_62 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.gridLayout_3.addWidget(self.label_62, 9, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label10.setFont(font)
        self.label10.setObjectName("label10")
        self.gridLayout_3.addWidget(self.label10, 3, 0, 1, 1)
        self.label11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label11.setFont(font)
        self.label11.setObjectName("label11")
        self.gridLayout_3.addWidget(self.label11, 4, 0, 1, 1)
        self.label13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label13.setFont(font)
        self.label13.setObjectName("label13")
        self.gridLayout_3.addWidget(self.label13, 6, 0, 1, 1)
        self.label17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label17.setFont(font)
        self.label17.setObjectName("label17")
        self.gridLayout_3.addWidget(self.label17, 10, 0, 1, 1)
        self.label18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label18.setFont(font)
        self.label18.setObjectName("label18")
        self.gridLayout_3.addWidget(self.label18, 11, 0, 1, 1)
        self.lineEdit22 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit22.setFont(font)
        self.lineEdit22.setObjectName("lineEdit22")
        self.gridLayout_3.addWidget(self.lineEdit22, 16, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit23 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit23.setFont(font)
        self.lineEdit23.setObjectName("lineEdit23")
        self.gridLayout_3.addWidget(self.lineEdit23, 17, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_60 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.gridLayout_3.addWidget(self.label_60, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_68 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")
        self.gridLayout_3.addWidget(self.label_68, 11, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label22 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label22.setFont(font)
        self.label22.setObjectName("label22")
        self.gridLayout_3.addWidget(self.label22, 15, 0, 1, 1)
        self.label24 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label24.setFont(font)
        self.label24.setObjectName("label24")
        self.gridLayout_3.addWidget(self.label24, 17, 0, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_82.setFont(font)
        self.label_82.setObjectName("label_82")
        self.gridLayout_3.addWidget(self.label_82, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label19.setFont(font)
        self.label19.setObjectName("label19")
        self.gridLayout_3.addWidget(self.label19, 12, 0, 1, 1)
        self.label7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label7.setFont(font)
        self.label7.setObjectName("label7")
        self.gridLayout_3.addWidget(self.label7, 0, 0, 1, 1)
        self.label16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label16.setFont(font)
        self.label16.setObjectName("label16")
        self.gridLayout_3.addWidget(self.label16, 9, 0, 1, 1)
        self.lineEdit10 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit10.setFont(font)
        self.lineEdit10.setObjectName("lineEdit10")
        self.gridLayout_3.addWidget(self.lineEdit10, 4, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit9 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit9.setFont(font)
        self.lineEdit9.setObjectName("lineEdit9")
        self.gridLayout_3.addWidget(self.lineEdit9, 3, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_74 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_74.setFont(font)
        self.label_74.setObjectName("label_74")
        self.gridLayout_3.addWidget(self.label_74, 17, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label8.setFont(font)
        self.label8.setObjectName("label8")
        self.gridLayout_3.addWidget(self.label8, 1, 0, 1, 1)
        self.lineEdit7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit7.setFont(font)
        self.lineEdit7.setObjectName("lineEdit7")
        self.gridLayout_3.addWidget(self.lineEdit7, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_83 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_83.setFont(font)
        self.label_83.setObjectName("label_83")
        self.gridLayout_3.addWidget(self.label_83, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label20.setFont(font)
        self.label20.setObjectName("label20")
        self.gridLayout_3.addWidget(self.label20, 13, 0, 1, 1)
        self.label_177 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_177.setFont(font)
        self.label_177.setObjectName("label_177")
        self.gridLayout_3.addWidget(self.label_177, 8, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit19 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit19.setFont(font)
        self.lineEdit19.setObjectName("lineEdit19")
        self.gridLayout_3.addWidget(self.lineEdit19, 13, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit21 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit21.setFont(font)
        self.lineEdit21.setObjectName("lineEdit21")
        self.gridLayout_3.addWidget(self.lineEdit21, 15, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit17 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit17.setFont(font)
        self.lineEdit17.setObjectName("lineEdit17")
        self.gridLayout_3.addWidget(self.lineEdit17, 11, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit20 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit20.setFont(font)
        self.lineEdit20.setObjectName("lineEdit20")
        self.gridLayout_3.addWidget(self.lineEdit20, 14, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit15 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit15.setFont(font)
        self.lineEdit15.setObjectName("lineEdit15")
        self.gridLayout_3.addWidget(self.lineEdit15, 9, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit18 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit18.setFont(font)
        self.lineEdit18.setObjectName("lineEdit18")
        self.gridLayout_3.addWidget(self.lineEdit18, 12, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit16 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit16.setFont(font)
        self.lineEdit16.setObjectName("lineEdit16")
        self.gridLayout_3.addWidget(self.lineEdit16, 10, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.gridLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.label_50 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout.addWidget(self.label_50, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit24 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit24.setFont(font)
        self.lineEdit24.setObjectName("lineEdit24")
        self.horizontalLayout.addWidget(self.lineEdit24, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem7)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_6.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(ROUE_VIS_SANS_FIN)
        QtCore.QMetaObject.connectSlotsByName(ROUE_VIS_SANS_FIN)

    def retranslateUi(self, ROUE_VIS_SANS_FIN):
        _translate = QtCore.QCoreApplication.translate
        ROUE_VIS_SANS_FIN.setWindowTitle(_translate("ROUE_VIS_SANS_FIN", "ROUE VIS SANS FIN"))
        self.label_2.setText(_translate("ROUE_VIS_SANS_FIN", "Valeurs d\'entrée"))
        self.label_30.setText(_translate("ROUE_VIS_SANS_FIN", "Zv"))
        self.label5.setText(_translate("ROUE_VIS_SANS_FIN", "Nombre de filets"))
        self.label_154.setText(_translate("ROUE_VIS_SANS_FIN", "q"))
        self.label_27.setText(_translate("ROUE_VIS_SANS_FIN", "∝"))
        self.label1.setText(_translate("ROUE_VIS_SANS_FIN", "Module normalisé"))
        self.label2.setText(_translate("ROUE_VIS_SANS_FIN", "Angle de pression reél"))
        self.label3.setText(_translate("ROUE_VIS_SANS_FIN", "Coefficient diamétral"))
        self.label_25.setText(_translate("ROUE_VIS_SANS_FIN", "m"))
        self.label4.setText(_translate("ROUE_VIS_SANS_FIN", "Nombre de dent roue"))
        self.label_170.setText(_translate("ROUE_VIS_SANS_FIN", "Zr"))
        self.label6.setText(_translate("ROUE_VIS_SANS_FIN", "Cofficient de friction"))
        self.label_49.setText(_translate("ROUE_VIS_SANS_FIN", "μ"))
        self.pushButton.setText(_translate("ROUE_VIS_SANS_FIN", "CALCULEZ"))
        self.pushButton_3.setText(_translate("ROUE_VIS_SANS_FIN", "SAUVEGARDER LES RESULTATS DU CALCUL"))
        self.label_45.setText(_translate("ROUE_VIS_SANS_FIN", "Valeurs de sortie"))
        self.label_41.setText(_translate("ROUE_VIS_SANS_FIN", "pt"))
        self.label_174.setText(_translate("ROUE_VIS_SANS_FIN", "pz"))
        self.label_63.setText(_translate("ROUE_VIS_SANS_FIN", "px"))
        self.label_53.setText(_translate("ROUE_VIS_SANS_FIN", "pn"))
        self.label_55.setText(_translate("ROUE_VIS_SANS_FIN", "L"))
        self.label_67.setText(_translate("ROUE_VIS_SANS_FIN", "h"))
        self.label_72.setText(_translate("ROUE_VIS_SANS_FIN", "∝x"))
        self.label_59.setText(_translate("ROUE_VIS_SANS_FIN", "dav"))
        self.label_71.setText(_translate("ROUE_VIS_SANS_FIN", "dfv"))
        self.label_178.setText(_translate("ROUE_VIS_SANS_FIN", "ha"))
        self.label23.setText(_translate("ROUE_VIS_SANS_FIN", "Longueur de la vis"))
        self.label21.setText(_translate("ROUE_VIS_SANS_FIN", "Diamètre de pied vis"))
        self.label15.setText(_translate("ROUE_VIS_SANS_FIN", "Diamètre primitive vis"))
        self.label12.setText(_translate("ROUE_VIS_SANS_FIN", "Pas axial vis"))
        self.label9.setText(_translate("ROUE_VIS_SANS_FIN", "Module axial vis"))
        self.label14.setText(_translate("ROUE_VIS_SANS_FIN", "Diamètre primitive roue"))
        self.label_176.setText(_translate("ROUE_VIS_SANS_FIN", "dr"))
        self.label_62.setText(_translate("ROUE_VIS_SANS_FIN", "a"))
        self.label10.setText(_translate("ROUE_VIS_SANS_FIN", "Pas réel roue"))
        self.label11.setText(_translate("ROUE_VIS_SANS_FIN", "Pas apparent roue"))
        self.label13.setText(_translate("ROUE_VIS_SANS_FIN", "Pas de l\'hélice"))
        self.label17.setText(_translate("ROUE_VIS_SANS_FIN", "Saillie"))
        self.label18.setText(_translate("ROUE_VIS_SANS_FIN", "Creux"))
        self.label_60.setText(_translate("ROUE_VIS_SANS_FIN", "mx"))
        self.label_68.setText(_translate("ROUE_VIS_SANS_FIN", "hf"))
        self.label22.setText(_translate("ROUE_VIS_SANS_FIN", "Angle de pression axial vis"))
        self.label24.setText(_translate("ROUE_VIS_SANS_FIN", "Largeur de la dent de la roue"))
        self.label_82.setText(_translate("ROUE_VIS_SANS_FIN", "βv"))
        self.label19.setText(_translate("ROUE_VIS_SANS_FIN", "Hauteur de la dent"))
        self.label7.setText(_translate("ROUE_VIS_SANS_FIN", "Angle d\'hélice vis"))
        self.label16.setText(_translate("ROUE_VIS_SANS_FIN", "Entraxe"))
        self.label_74.setText(_translate("ROUE_VIS_SANS_FIN", "b"))
        self.label8.setText(_translate("ROUE_VIS_SANS_FIN", "Angle d\'hélice roue"))
        self.label_83.setText(_translate("ROUE_VIS_SANS_FIN", "βr"))
        self.label20.setText(_translate("ROUE_VIS_SANS_FIN", "Diamètre de tête vis"))
        self.label_177.setText(_translate("ROUE_VIS_SANS_FIN", "dv"))
        self.label_8.setText(_translate("ROUE_VIS_SANS_FIN", "Le rendement"))
        self.label_50.setText(_translate("ROUE_VIS_SANS_FIN", "η"))
        self.pushButton_2.setText(_translate("ROUE_VIS_SANS_FIN", "RETOUR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ROUE_VIS_SANS_FIN = QtWidgets.QWidget()
    ui = Ui_ROUE_VIS_SANS_FIN()
    ui.setupUi(ROUE_VIS_SANS_FIN)
    ROUE_VIS_SANS_FIN.show()
    sys.exit(app.exec_())
