
from PyQt5 import QtCore, QtGui, QtWidgets
import math
from PyQt5.QtWidgets import QMessageBox
import openpyxl

class Ui_Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE(object):


    def calculer_engrenage(self):
        try:
            
            M = float(self.lineEdit1.text()) 
            A_P = int(self.lineEdit2.text())   
            Z1 = int(self.lineEdit3.text())
            Z2 = int(self.lineEdit4.text()) 
            X1 = float(self.lineEdit5.text())
            X2 = float(self.lineEdit6.text())
            μ = float(self.lineEdit_mi.text())
                                    
            U = float(Z2 / Z1)
            i = float(-(Z1 / Z2))
            
            A1 = math.tan(math.radians(A_P)) 
            #A2 = math.degrees(A1)

            inv_A_P = math.tan(math.radians(A_P)) - ((math.pi*A_P)/180) 
            inv_alpha_p = inv_A_P + 2*((X1+X2)/(Z2+Z1)) * A1

            INV = ((3*inv_alpha_p)**(1/3))-((2*inv_alpha_p)/5)+(9/175)*((3)**(2/3))*((inv_alpha_p)**(5/3))-(2/175)*(3**(1/3))*(inv_alpha_p**(7/3))-(144/67375)*(inv_alpha_p**(3))+(3258/3128125)*(3**(2/3))*(inv_alpha_p**(11/3))-(49711/153278125)*(3**(1/3))*(inv_alpha_p**(13/3))
            alpha_p = math.degrees(INV)

            A3 = math.cos(math.radians(A_P))
            A4 = math.degrees(A3)

            A5 = math.cos(math.radians(alpha_p))
            A6 = math.degrees(A5)

            M_P = (A3/A5) * M

            p = math.pi*M

            pb = p*A3
            pb = float(pb)

            a = ((Z2+Z1)/2) * M

            a_p = a*(A3/A5)

            d1 = Z1*M 
            d2 = Z2*M

            dpf1 = Z1*M_P

            dpf2 = Z2*M_P

            K = ((Z2+Z1)/2) * (2*((X1 + X2)/(Z1 + Z2)) - ((a_p/a) - 1))

            da1 = float(d1+2*(1+X1-K)*M) 
            da2 = float(d2+2*(1+X2-K)*M)

            df1 = float(d1-2*(1.25-X1)*M) 
            df2 = float(d2-2*(1.25-X2)*M)

            db1 = float(d1*A3)
            db2 = float(d2*A3)

            Ha1 = float(1+X1-K)*M
            Ha2 = float(1+X2-K)*M

            Hf1 = float(1.25-X1)*M
            Hf2 = float(1.25-X2)*M

            h = 2.25*M

            A7 = float(math.acos((db1/da1)))
            A8 = float(math.acos((db2/da2)))
            Alpha_a1 = math.degrees(A7)
            Alpha_a2 = math.degrees(A8)

            A9 = math.tan(math.radians(A_P))
            s1 = M*((math.pi/2)+ 2* X1* A9)
            s2 = M*((math.pi/2)+ 2* X2* A9)

            sp1 = dpf1*((s1/d1) + inv_A_P - inv_alpha_p)
            sp2 = dpf2*((s2/d2) + inv_A_P - inv_alpha_p)

            inv_a11 = (math.tan(math.radians(Alpha_a1))) - A7
            inv_a12 = (math.tan(math.radians(Alpha_a2))) - A8 
            sa1 = da1*((s1/d1) + inv_A_P - inv_a11)
            sa2 = da2*((s2/d2) + inv_A_P - inv_a12)

            sb1 = db1*((s1/d1)+ inv_A_P)
            sb2 = db2*((s2/d2)+ inv_A_P)

            Delta1 = X1*M
            Delta2 = X2*M

            A10 = math.tan(math.radians(Alpha_a1))

            A11 = math.tan(math.radians(Alpha_a2))

            A12 = math.tan(math.radians(alpha_p))

            E1 = (Z1/(2*math.pi))*(A10 - A12)
            E2 = (Z2/(2*math.pi))*(A11 - A12)

            E_alpha = E1+E2

            ga1 = E1*pb
            ga2 = E2*pb

            g_alpha = ga1+ga2

            gt = g_alpha/ A3

            r = 1 - μ * ((U+1)/U) * (math.pi/Z1) * (1 + (E1**2) + (E2**2) - E_alpha)
            r_p = 100 * r
            
        except ValueError:
            QMessageBox.warning(None, "Erreur de saisie", "Il est impossible d'effectuer le calcul. Vérifiez les valeurs d'entrée.")
            return
        except ZeroDivisionError:
            QMessageBox.warning(None, "Erreur de saisie", "Il est impossible d'effectuer le calcul. Vérifiez les valeurs d'entrée.")
            return

        # Affichage des resultats dans les LineEdit
        self.lineEdit7.setText(str(U))
        self.lineEdit8.setText(str(i))
        self.lineEdit9.setText(str(alpha_p))
        self.lineEdit10.setText(str(M_P))
        self.lineEdit11.setText(str(p))
        self.lineEdit12.setText(str(pb))
        self.lineEdit12_1.setText(str(a))
        self.lineEdit13.setText(str(a_p))
        self.lineEdit14.setText(str(d1))
        self.lineEdit15.setText(str(d2))
        self.lineEdit16.setText(str(dpf1))
        self.lineEdit17.setText(str(dpf2))
        self.lineEdit18.setText(str(da1))
        self.lineEdit19.setText(str(da2))
        self.lineEdit20.setText(str(df1))
        self.lineEdit21.setText(str(df2))
        self.lineEdit22.setText(str(db1))
        self.lineEdit23.setText(str(db2))
        self.lineEdit24.setText(str(Ha1))
        self.lineEdit25.setText(str(Ha2))
        self.lineEdit26.setText(str(Hf1))
        self.lineEdit27.setText(str(Hf2))
        self.lineEdit28.setText(str(h))
        self.lineEdit29.setText(str(Alpha_a1))
        self.lineEdit30.setText(str(Alpha_a2))
        self.lineEdit31.setText(str(s1))
        self.lineEdit32.setText(str(s2))
        self.lineEdit33.setText(str(sp1))
        self.lineEdit34.setText(str(sp2))
        self.lineEdit35.setText(str(sa1))
        self.lineEdit36.setText(str(sa2))
        self.lineEdit37.setText(str(sb1))
        self.lineEdit38.setText(str(sb2))
        self.lineEdit39.setText(str(Delta1))
        self.lineEdit40.setText(str(Delta2))
        self.lineEdit41.setText(str(E1))
        self.lineEdit42.setText(str(E2))
        self.lineEdit43.setText(str(E_alpha))
        self.lineEdit44.setText(str(ga1))
        self.lineEdit45.setText(str(ga2))
        self.lineEdit46.setText(str(g_alpha))
        self.lineEdit47.setText(str(gt))
        self.lineEdit48.setText(str(r_p))

    def sauvegarder_dans_excel(self):
        wb = openpyxl.Workbook()
        ws = wb.active

        noms_labels = [
            self.label1.text(),
            self.label2.text(),
            self.label3.text(),
            self.label3.text(),
            self.label4.text(),
            self.label4.text(),
            self.label_mi.text(),
            self.label5.text(),
            self.label6.text(),
            self.label7.text(),
            self.label8.text(),
            self.label9.text(),
            self.label10.text(),
            self.label10_1.text(),
            self.label11.text(),
            self.label12.text(),
            self.label12.text(),
            self.label13.text(),
            self.label13.text(),
            self.label14.text(),
            self.label14.text(),
            self.label15.text(),
            self.label15.text(),
            self.label16.text(),
            self.label16.text(),
            self.label17.text(),
            self.label17.text(),
            self.label18.text(),
            self.label18.text(),
            self.label19.text(),
            self.label20.text(),
            self.label20.text(),
            self.label21.text(),
            self.label21.text(),
            self.label22.text(),
            self.label22.text(),
            self.label23.text(),
            self.label23.text(),
            self.label24.text(),
            self.label24.text(),
            self.label25.text(),
            self.label25.text(),
            self.label26.text(),
            self.label26.text(),
            self.label27.text(),
            self.label28.text(),
            self.label28.text(),
            self.label29.text(),
            self.label30.text(),
            self.label31.text(),
        ]

        symboles = [
            "m", "∝", "Z1", "Z2", "X1", "X2", "μ", "U", "i", "∝'", "m'", "p", "pb", "a", "a'", "d1", "d2", "d1'", "d2'",
            "da1", "da2", "df1", "df2", "db1", "db2", "ha1", "ha2", "hf1", "hf2", "h", "∝a1", "∝a2", "s1", "s2",
            "s1'", "s2'", "sa1", "sa2", "sb1", "sb2", "δ1", "δ2", "ε1", "ε2", "ε∝", "ga1", "ga2", "g∝", "gt", "ηméc"
            
        ]


        valeurs = [


            self.lineEdit1.text(), 
            self.lineEdit2.text(),  
            self.lineEdit3.text(),
            self.lineEdit4.text(),
            self.lineEdit5.text(),
            self.lineEdit6.text(),
            self.lineEdit_mi.text(),
            self.lineEdit7.text(),
            self.lineEdit8.text(),
            self.lineEdit9.text(),
            self.lineEdit10.text(),
            self.lineEdit11.text(),
            self.lineEdit12.text(),
            self.lineEdit12_1.text(),
            self.lineEdit13.text(),
            self.lineEdit14.text(),
            self.lineEdit15.text(),
            self.lineEdit16.text(),
            self.lineEdit17.text(),
            self.lineEdit18.text(),
            self.lineEdit19.text(),
            self.lineEdit20.text(),
            self.lineEdit21.text(),
            self.lineEdit22.text(),
            self.lineEdit23.text(),
            self.lineEdit24.text(),
            self.lineEdit25.text(),
            self.lineEdit26.text(),
            self.lineEdit27.text(),
            self.lineEdit28.text(),
            self.lineEdit29.text(),
            self.lineEdit30.text(),
            self.lineEdit31.text(),
            self.lineEdit32.text(),
            self.lineEdit33.text(),
            self.lineEdit34.text(),
            self.lineEdit35.text(),
            self.lineEdit36.text(),
            self.lineEdit37.text(),
            self.lineEdit38.text(),
            self.lineEdit39.text(),
            self.lineEdit40.text(),
            self.lineEdit41.text(),
            self.lineEdit42.text(),
            self.lineEdit43.text(),
            self.lineEdit44.text(),
            self.lineEdit45.text(),
            self.lineEdit46.text(),
            self.lineEdit47.text(),
            self.lineEdit48.text(),
            
        ]

        unites = ["mm", "degré", "", "", "", "", "", "", "", "degré", "mm", "mm", "mm", "mm", "mm", "mm", "mm", 
            "mm", "mm", "mm","mm", "mm", "mm", "mm", "mm", "mm", "mm", "mm", "mm", "mm", "degré", "degré", "mm", 
            "mm", "mm", "mm", "mm", "mm", "mm","mm", "mm", "mm", "", "" , "", "mm" , "mm" , "mm" , "mm", "%"
        ]

        entete = ['Nom(s)', 'Symbole(s)', 'Valeur(s)', 'Unité(s)']
        ws.append(entete)

        for i in range(len(noms_labels)):
            ws.append([noms_labels[i], symboles[i], valeurs[i], unites[i]])

        for row in ws.iter_rows(min_row=1, max_row=51, min_col=1, max_col=4):
            for cell in row:
                cell.border = openpyxl.styles.Border(
                    left=openpyxl.styles.Side(border_style='thin'),
                    right=openpyxl.styles.Side(border_style='thin'),
                    top=openpyxl.styles.Side(border_style='thin'),
                    bottom=openpyxl.styles.Side(border_style='thin')
                )

        for row in ws.iter_rows(min_row=1, max_row=1, min_col=1, max_col=4):
            for cell in row:
                cell.fill = openpyxl.styles.PatternFill(start_color="0070C0", end_color="0070C0", fill_type="solid")
                cell.font = openpyxl.styles.Font(color="FFFFFF", bold=True)


        file_path, _ = QtWidgets.QFileDialog.getSaveFileName(None, "Enregistrer le fichier Excel", "", "Excel Files (*.xlsx)")
        if file_path:
            wb.save(file_path)
            QtWidgets.QMessageBox.information(None, "Enregistrement", "Fichier Excel enregistré avec succès !")




    def setupUi(self, Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE):
        Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE.setObjectName("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE")
        Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE.resize(579, 383)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("reducteur_gearexpert.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -457, 595, 1302))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.lineEdit3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit3.setFont(font)
        self.lineEdit3.setObjectName("lineEdit3")
        self.gridLayout_2.addWidget(self.lineEdit3, 2, 2, 1, 1)
        self.lineEdit5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit5.setFont(font)
        self.lineEdit5.setObjectName("lineEdit5")
        self.gridLayout_2.addWidget(self.lineEdit5, 3, 2, 1, 1)
        self.lineEdit4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit4.setFont(font)
        self.lineEdit4.setObjectName("lineEdit4")
        self.gridLayout_2.addWidget(self.lineEdit4, 2, 4, 1, 1)
        self.lineEdit2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit2.setFont(font)
        self.lineEdit2.setObjectName("lineEdit2")
        self.gridLayout_2.addWidget(self.lineEdit2, 1, 2, 1, 1)
        self.lineEdit1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit1.setFont(font)
        self.lineEdit1.setObjectName("lineEdit1")
        self.gridLayout_2.addWidget(self.lineEdit1, 0, 2, 1, 1)
        self.label3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.gridLayout_2.addWidget(self.label3, 2, 0, 1, 1)
        self.label1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.gridLayout_2.addWidget(self.label1, 0, 0, 1, 1)
        self.lineEdit6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit6.setFont(font)
        self.lineEdit6.setObjectName("lineEdit6")
        self.gridLayout_2.addWidget(self.lineEdit6, 3, 4, 1, 1)
        self.label2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.gridLayout_2.addWidget(self.label2, 1, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 1, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.gridLayout_2.addWidget(self.label_46, 2, 3, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.gridLayout_2.addWidget(self.label_47, 3, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.gridLayout_2.addWidget(self.label_48, 3, 3, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 2, 1, 1, 1)
        self.label4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label4.setFont(font)
        self.label4.setObjectName("label4")
        self.gridLayout_2.addWidget(self.label4, 3, 0, 1, 1)
        self.label_mi = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_mi.setFont(font)
        self.label_mi.setObjectName("label_mi")
        self.gridLayout_2.addWidget(self.label_mi, 4, 0, 1, 1)
        self.label_mi_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_mi_1.setFont(font)
        self.label_mi_1.setObjectName("label_mi_1")
        self.gridLayout_2.addWidget(self.label_mi_1, 4, 1, 1, 1)
        self.lineEdit_mi = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_mi.setFont(font)
        self.lineEdit_mi.setObjectName("lineEdit_mi")
        self.gridLayout_2.addWidget(self.lineEdit_mi, 4, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setMaximumSize(QtCore.QSize(180, 180))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.calculer_engrenage) # Liaison du clic du bouton à la fonction de calcul
        ####################################################################################################

        self.verticalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")

        self.pushButton_3.clicked.connect(self.sauvegarder_dans_excel)  # Connecte le clic du bouton à la fonction de sauvegarde
        ##############################################################################################################

        self.verticalLayout.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem2)
        self.label_45 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.verticalLayout.addWidget(self.label_45, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label6.setFont(font)
        self.label6.setObjectName("label6")
        self.gridLayout_3.addWidget(self.label6, 1, 0, 1, 1)
        self.lineEdit29 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit29.setFont(font)
        self.lineEdit29.setObjectName("lineEdit29")
        self.gridLayout_3.addWidget(self.lineEdit29, 16, 2, 1, 1)
        self.label21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label21.setFont(font)
        self.label21.setObjectName("label21")
        self.gridLayout_3.addWidget(self.label21, 17, 0, 1, 1)
        self.lineEdit7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit7.setFont(font)
        self.lineEdit7.setObjectName("lineEdit7")
        self.gridLayout_3.addWidget(self.lineEdit7, 0, 2, 1, 1)
        self.lineEdit19 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit19.setFont(font)
        self.lineEdit19.setObjectName("lineEdit19")
        self.gridLayout_3.addWidget(self.lineEdit19, 10, 4, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.gridLayout_3.addWidget(self.label_59, 11, 1, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_82.setFont(font)
        self.label_82.setObjectName("label_82")
        self.gridLayout_3.addWidget(self.label_82, 0, 1, 1, 1)
        self.lineEdit22 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit22.setFont(font)
        self.lineEdit22.setObjectName("lineEdit22")
        self.gridLayout_3.addWidget(self.lineEdit22, 12, 2, 1, 1)
        self.label5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label5.setFont(font)
        self.label5.setObjectName("label5")
        self.gridLayout_3.addWidget(self.label5, 0, 0, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.gridLayout_3.addWidget(self.label_53, 13, 1, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_83.setFont(font)
        self.label_83.setObjectName("label_83")
        self.gridLayout_3.addWidget(self.label_83, 1, 1, 1, 1)
        self.lineEdit8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit8.setFont(font)
        self.lineEdit8.setObjectName("lineEdit8")
        self.gridLayout_3.addWidget(self.lineEdit8, 1, 2, 1, 1)
        self.label18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label18.setFont(font)
        self.label18.setObjectName("label18")
        self.gridLayout_3.addWidget(self.label18, 14, 0, 1, 1)
        self.lineEdit16 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit16.setFont(font)
        self.lineEdit16.setObjectName("lineEdit16")
        self.gridLayout_3.addWidget(self.lineEdit16, 9, 2, 1, 1)
        self.label20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label20.setFont(font)
        self.label20.setObjectName("label20")
        self.gridLayout_3.addWidget(self.label20, 16, 0, 1, 1)
        self.lineEdit31 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit31.setFont(font)
        self.lineEdit31.setObjectName("lineEdit31")
        self.gridLayout_3.addWidget(self.lineEdit31, 17, 2, 1, 1)
        self.lineEdit28 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit28.setFont(font)
        self.lineEdit28.setObjectName("lineEdit28")
        self.gridLayout_3.addWidget(self.lineEdit28, 15, 2, 1, 1)
        self.lineEdit27 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit27.setFont(font)
        self.lineEdit27.setObjectName("lineEdit27")
        self.gridLayout_3.addWidget(self.lineEdit27, 14, 4, 1, 1)
        self.label26 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label26.setFont(font)
        self.label26.setObjectName("label26")
        self.gridLayout_3.addWidget(self.label26, 22, 0, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_70.setFont(font)
        self.label_70.setObjectName("label_70")
        self.gridLayout_3.addWidget(self.label_70, 9, 3, 1, 1)
        self.label17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label17.setFont(font)
        self.label17.setObjectName("label17")
        self.gridLayout_3.addWidget(self.label17, 13, 0, 1, 1)
        self.lineEdit23 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit23.setFont(font)
        self.lineEdit23.setObjectName("lineEdit23")
        self.gridLayout_3.addWidget(self.lineEdit23, 12, 4, 1, 1)
        self.lineEdit25 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit25.setFont(font)
        self.lineEdit25.setObjectName("lineEdit25")
        self.gridLayout_3.addWidget(self.lineEdit25, 13, 4, 1, 1)
        self.lineEdit42 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit42.setFont(font)
        self.lineEdit42.setObjectName("lineEdit42")
        self.gridLayout_3.addWidget(self.lineEdit42, 22, 4, 1, 1)
        self.lineEdit21 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit21.setFont(font)
        self.lineEdit21.setObjectName("lineEdit21")
        self.gridLayout_3.addWidget(self.lineEdit21, 11, 4, 1, 1)
        self.lineEdit32 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit32.setFont(font)
        self.lineEdit32.setObjectName("lineEdit32")
        self.gridLayout_3.addWidget(self.lineEdit32, 17, 4, 1, 1)
        self.lineEdit30 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit30.setFont(font)
        self.lineEdit30.setObjectName("lineEdit30")
        self.gridLayout_3.addWidget(self.lineEdit30, 16, 4, 1, 1)
        self.lineEdit36 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit36.setFont(font)
        self.lineEdit36.setObjectName("lineEdit36")
        self.gridLayout_3.addWidget(self.lineEdit36, 19, 4, 1, 1)
        self.lineEdit34 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit34.setFont(font)
        self.lineEdit34.setObjectName("lineEdit34")
        self.gridLayout_3.addWidget(self.lineEdit34, 18, 4, 1, 1)
        self.lineEdit40 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit40.setFont(font)
        self.lineEdit40.setObjectName("lineEdit40")
        self.gridLayout_3.addWidget(self.lineEdit40, 21, 4, 1, 1)
        self.lineEdit38 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit38.setFont(font)
        self.lineEdit38.setObjectName("lineEdit38")
        self.gridLayout_3.addWidget(self.lineEdit38, 20, 4, 1, 1)
        self.lineEdit17 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit17.setFont(font)
        self.lineEdit17.setObjectName("lineEdit17")
        self.gridLayout_3.addWidget(self.lineEdit17, 9, 4, 1, 1)
        self.lineEdit15 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit15.setFont(font)
        self.lineEdit15.setObjectName("lineEdit15")
        self.gridLayout_3.addWidget(self.lineEdit15, 8, 4, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.gridLayout_3.addWidget(self.label_39, 2, 1, 1, 1)
        self.label28 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label28.setFont(font)
        self.label28.setObjectName("label28")
        self.gridLayout_3.addWidget(self.label28, 24, 0, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.gridLayout_3.addWidget(self.label_65, 24, 1, 1, 1)
        self.lineEdit45 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit45.setFont(font)
        self.lineEdit45.setObjectName("lineEdit45")
        self.gridLayout_3.addWidget(self.lineEdit45, 24, 4, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.gridLayout_3.addWidget(self.label_52, 16, 1, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.gridLayout_3.addWidget(self.label_66, 23, 1, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.gridLayout_3.addWidget(self.label_54, 25, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.gridLayout_3.addWidget(self.label_57, 21, 1, 1, 1)
        self.label15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label15.setFont(font)
        self.label15.setObjectName("label15")
        self.gridLayout_3.addWidget(self.label15, 11, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.gridLayout_3.addWidget(self.label_36, 3, 1, 1, 1)
        self.lineEdit43 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit43.setFont(font)
        self.lineEdit43.setObjectName("lineEdit43")
        self.gridLayout_3.addWidget(self.lineEdit43, 23, 2, 1, 1)
        self.label24 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label24.setFont(font)
        self.label24.setObjectName("label24")
        self.gridLayout_3.addWidget(self.label24, 20, 0, 1, 1)
        self.label19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label19.setFont(font)
        self.label19.setObjectName("label19")
        self.gridLayout_3.addWidget(self.label19, 15, 0, 1, 1)
        self.label9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label9.setFont(font)
        self.label9.setObjectName("label9")
        self.gridLayout_3.addWidget(self.label9, 4, 0, 1, 1)
        self.lineEdit46 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit46.setFont(font)
        self.lineEdit46.setObjectName("lineEdit46")
        self.gridLayout_3.addWidget(self.lineEdit46, 25, 2, 1, 1)
        self.label14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label14.setFont(font)
        self.label14.setObjectName("label14")
        self.gridLayout_3.addWidget(self.label14, 10, 0, 1, 1)
        self.lineEdit14 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit14.setFont(font)
        self.lineEdit14.setObjectName("lineEdit14")
        self.gridLayout_3.addWidget(self.lineEdit14, 8, 2, 1, 1)
        self.lineEdit10 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit10.setFont(font)
        self.lineEdit10.setObjectName("lineEdit10")
        self.gridLayout_3.addWidget(self.lineEdit10, 3, 2, 1, 1)
        self.label23 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label23.setFont(font)
        self.label23.setObjectName("label23")
        self.gridLayout_3.addWidget(self.label23, 19, 0, 1, 1)
        self.lineEdit9 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit9.setFont(font)
        self.lineEdit9.setObjectName("lineEdit9")
        self.gridLayout_3.addWidget(self.lineEdit9, 2, 2, 1, 1)
        self.lineEdit41 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit41.setFont(font)
        self.lineEdit41.setObjectName("lineEdit41")
        self.gridLayout_3.addWidget(self.lineEdit41, 22, 2, 1, 1)
        self.lineEdit35 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit35.setFont(font)
        self.lineEdit35.setObjectName("lineEdit35")
        self.gridLayout_3.addWidget(self.lineEdit35, 19, 2, 1, 1)
        self.lineEdit37 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit37.setFont(font)
        self.lineEdit37.setObjectName("lineEdit37")
        self.gridLayout_3.addWidget(self.lineEdit37, 20, 2, 1, 1)
        self.lineEdit39 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit39.setFont(font)
        self.lineEdit39.setObjectName("lineEdit39")
        self.gridLayout_3.addWidget(self.lineEdit39, 21, 2, 1, 1)
        self.lineEdit44 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit44.setFont(font)
        self.lineEdit44.setObjectName("lineEdit44")
        self.gridLayout_3.addWidget(self.lineEdit44, 24, 2, 1, 1)
        self.lineEdit13 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit13.setFont(font)
        self.lineEdit13.setObjectName("lineEdit13")
        self.gridLayout_3.addWidget(self.lineEdit13, 7, 2, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_76.setFont(font)
        self.label_76.setObjectName("label_76")
        self.gridLayout_3.addWidget(self.label_76, 18, 3, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_78.setFont(font)
        self.label_78.setObjectName("label_78")
        self.gridLayout_3.addWidget(self.label_78, 20, 3, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_74.setFont(font)
        self.label_74.setObjectName("label_74")
        self.gridLayout_3.addWidget(self.label_74, 16, 3, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_79.setFont(font)
        self.label_79.setObjectName("label_79")
        self.gridLayout_3.addWidget(self.label_79, 21, 3, 1, 1)
        self.lineEdit18 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit18.setFont(font)
        self.lineEdit18.setObjectName("lineEdit18")
        self.gridLayout_3.addWidget(self.lineEdit18, 10, 2, 1, 1)
        self.label11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label11.setFont(font)
        self.label11.setObjectName("label11")
        self.gridLayout_3.addWidget(self.label11, 7, 0, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.gridLayout_3.addWidget(self.label_63, 15, 1, 1, 1)
        self.label25 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label25.setFont(font)
        self.label25.setObjectName("label25")
        self.gridLayout_3.addWidget(self.label25, 21, 0, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.gridLayout_3.addWidget(self.label_69, 8, 3, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.gridLayout_3.addWidget(self.label_67, 10, 1, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.gridLayout_3.addWidget(self.label_62, 4, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.gridLayout_3.addWidget(self.label_58, 20, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.gridLayout_3.addWidget(self.label_44, 18, 1, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_71.setFont(font)
        self.label_71.setObjectName("label_71")
        self.gridLayout_3.addWidget(self.label_71, 10, 3, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.gridLayout_3.addWidget(self.label_43, 19, 1, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")
        self.gridLayout_3.addWidget(self.label_68, 9, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.gridLayout_3.addWidget(self.label_41, 14, 1, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.gridLayout_3.addWidget(self.label_50, 5, 1, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.gridLayout_3.addWidget(self.label_61, 7, 1, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.gridLayout_3.addWidget(self.label_49, 12, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.gridLayout_3.addWidget(self.label_56, 13, 3, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.gridLayout_3.addWidget(self.label_55, 12, 3, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_75.setFont(font)
        self.label_75.setObjectName("label_75")
        self.gridLayout_3.addWidget(self.label_75, 17, 3, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_72.setFont(font)
        self.label_72.setObjectName("label_72")
        self.gridLayout_3.addWidget(self.label_72, 11, 3, 1, 1)
        self.label30 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label30.setFont(font)
        self.label30.setObjectName("label30")
        self.gridLayout_3.addWidget(self.label30, 26, 0, 1, 1)
        self.label22 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label22.setFont(font)
        self.label22.setObjectName("label22")
        self.gridLayout_3.addWidget(self.label22, 18, 0, 1, 1)
        self.label10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label10.setFont(font)
        self.label10.setObjectName("label10")
        self.gridLayout_3.addWidget(self.label10, 5, 0, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_73.setFont(font)
        self.label_73.setObjectName("label_73")
        self.gridLayout_3.addWidget(self.label_73, 14, 3, 1, 1)
        self.label7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label7.setFont(font)
        self.label7.setObjectName("label7")
        self.gridLayout_3.addWidget(self.label7, 2, 0, 1, 1)
        self.label29 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label29.setFont(font)
        self.label29.setObjectName("label29")
        self.gridLayout_3.addWidget(self.label29, 25, 0, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_81.setFont(font)
        self.label_81.setObjectName("label_81")
        self.gridLayout_3.addWidget(self.label_81, 24, 3, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.gridLayout_3.addWidget(self.label_60, 8, 1, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_77.setFont(font)
        self.label_77.setObjectName("label_77")
        self.gridLayout_3.addWidget(self.label_77, 19, 3, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_80.setFont(font)
        self.label_80.setObjectName("label_80")
        self.gridLayout_3.addWidget(self.label_80, 22, 3, 1, 1)
        self.lineEdit24 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit24.setFont(font)
        self.lineEdit24.setObjectName("lineEdit24")
        self.gridLayout_3.addWidget(self.lineEdit24, 13, 2, 1, 1)
        self.label12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label12.setFont(font)
        self.label12.setObjectName("label12")
        self.gridLayout_3.addWidget(self.label12, 8, 0, 1, 1)
        self.label13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label13.setFont(font)
        self.label13.setObjectName("label13")
        self.gridLayout_3.addWidget(self.label13, 9, 0, 1, 1)
        self.lineEdit12 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit12.setFont(font)
        self.lineEdit12.setObjectName("lineEdit12")
        self.gridLayout_3.addWidget(self.lineEdit12, 5, 2, 1, 1)
        self.label27 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label27.setFont(font)
        self.label27.setObjectName("label27")
        self.gridLayout_3.addWidget(self.label27, 23, 0, 1, 1)
        self.label16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label16.setFont(font)
        self.label16.setObjectName("label16")
        self.gridLayout_3.addWidget(self.label16, 12, 0, 1, 1)
        self.lineEdit47 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit47.setFont(font)
        self.lineEdit47.setObjectName("lineEdit47")
        self.gridLayout_3.addWidget(self.lineEdit47, 26, 2, 1, 1)
        self.lineEdit26 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit26.setFont(font)
        self.lineEdit26.setObjectName("lineEdit26")
        self.gridLayout_3.addWidget(self.lineEdit26, 14, 2, 1, 1)
        self.lineEdit20 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit20.setFont(font)
        self.lineEdit20.setObjectName("lineEdit20")
        self.gridLayout_3.addWidget(self.lineEdit20, 11, 2, 1, 1)
        self.lineEdit33 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit33.setFont(font)
        self.lineEdit33.setObjectName("lineEdit33")
        self.gridLayout_3.addWidget(self.lineEdit33, 18, 2, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.gridLayout_3.addWidget(self.label_64, 22, 1, 1, 1)
        self.label8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label8.setFont(font)
        self.label8.setObjectName("label8")
        self.gridLayout_3.addWidget(self.label8, 3, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.gridLayout_3.addWidget(self.label_42, 26, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.gridLayout_3.addWidget(self.label_51, 17, 1, 1, 1)
        self.lineEdit11 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit11.setFont(font)
        self.lineEdit11.setObjectName("lineEdit11")
        self.gridLayout_3.addWidget(self.lineEdit11, 4, 2, 1, 1)
        self.label10_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label10_1.setFont(font)
        self.label10_1.setObjectName("label10_1")
        self.gridLayout_3.addWidget(self.label10_1, 6, 0, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_84.setFont(font)
        self.label_84.setObjectName("label_84")
        self.gridLayout_3.addWidget(self.label_84, 6, 1, 1, 1)
        self.lineEdit12_1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit12_1.setFont(font)
        self.lineEdit12_1.setObjectName("lineEdit12_1")
        self.gridLayout_3.addWidget(self.lineEdit12_1, 6, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem5)
        self.label31 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label31.setFont(font)
        self.label31.setObjectName("label31")
        self.verticalLayout.addWidget(self.label31, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label32 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label32.setFont(font)
        self.label32.setObjectName("label32")
        self.horizontalLayout.addWidget(self.label32, 0, QtCore.Qt.AlignRight)
        self.lineEdit48 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit48.setFont(font)
        self.lineEdit48.setObjectName("lineEdit48")
        self.horizontalLayout.addWidget(self.lineEdit48, 0, QtCore.Qt.AlignHCenter)
        self.label_37 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout.addWidget(self.label_37, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem7)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE)
        QtCore.QMetaObject.connectSlotsByName(Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE)

    def retranslateUi(self, Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE):
        _translate = QtCore.QCoreApplication.translate
        Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE.setWindowTitle(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Denture doite deporte exterieur variation entraxe non_impose"))
        self.label_2.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Valeurs d\'entrée"))
        self.label_3.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "m"))
        self.label3.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Nombre de dent"))
        self.label1.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Module normalisé"))
        self.label2.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Angle de pression normalisé"))
        self.label_27.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "∝"))
        self.label_46.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Z2"))
        self.label_47.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "X1"))
        self.label_48.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "X2"))
        self.label_30.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Z1"))
        self.label4.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Les déports"))
        self.label_mi.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Le coefficient de frottement"))
        self.label_mi_1.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "μ"))
        self.pushButton.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "CALCULEZ"))
        self.pushButton_3.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "SAUVEGARDER LES RESULTATS DU CALCUL"))
        self.label_45.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Valeurs de sortie"))
        self.label6.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Le rapport de transmission"))
        self.label21.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Epaisseur curviligne au primitif"))
        self.label_59.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "df1"))
        self.label_82.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "U"))
        self.label5.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Le rapport d\'engrenage"))
        self.label_53.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "ha1"))
        self.label_83.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "i"))
        self.label18.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Creux de fonctionnement"))
        self.label20.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Angle de pression de tête"))
        self.label26.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Rapport de conduite partiel de retraite "))
        self.label_70.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "d2\'"))
        self.label17.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Saillie de fonctionnememt"))
        self.label_39.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "∝\'"))
        self.label28.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Longueur partielle de retraite"))
        self.label_65.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "ga1"))
        self.label_52.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "∝a1"))
        self.label_66.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "ε∝"))
        self.label_54.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "g∝"))
        self.label_57.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "δ1"))
        self.label15.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Diamètre de pied"))
        self.label_36.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "m\'"))
        self.label24.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Epaisseur curviligne au cercle de base"))
        self.label19.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Hauteur "))
        self.label9.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Pas au primitif"))
        self.label14.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Diamètre de tête"))
        self.label23.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Epaisseur curviligne au cercle de tête"))
        self.label_76.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "s2\'"))
        self.label_78.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "sb2"))
        self.label_74.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "∝a2"))
        self.label_79.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "δ2"))
        self.label11.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Entraxe de fonctionnement"))
        self.label_63.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "h"))
        self.label25.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Déport de denture"))
        self.label_69.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "d2"))
        self.label_67.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "da1"))
        self.label_62.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "p"))
        self.label_58.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "sb1"))
        self.label_44.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "s1\'"))
        self.label_71.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "da2"))
        self.label_43.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "sa1"))
        self.label_68.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "d1\'"))
        self.label_41.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "hf1"))
        self.label_50.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "pb"))
        self.label_61.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "a\'"))
        self.label_49.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "db1"))
        self.label_56.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "ha2"))
        self.label_55.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "db2"))
        self.label_75.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "s2"))
        self.label_72.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "df2"))
        self.label30.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Arc de conduite"))
        self.label22.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Epaisseur curviligne au primitif de fonctionnement"))
        self.label10.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Pas de base"))
        self.label_73.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "hf2"))
        self.label7.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Angle de pression de fonctionnement"))
        self.label29.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Longueur totale de conduite"))
        self.label_81.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "ga2"))
        self.label_60.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "d1"))
        self.label_77.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "sa2"))
        self.label_80.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "ε2"))
        self.label12.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Diamètre primitif"))
        self.label13.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Diamètre primitif de fonctionnement"))
        self.label27.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Rapport de conduite total"))
        self.label16.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Diamètre de base"))
        self.label_64.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "ε1"))
        self.label8.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Module de fonctionnement"))
        self.label_42.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "gt"))
        self.label_51.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "s1"))
        self.label10_1.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Entraxe"))
        self.label_84.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "a"))
        self.label31.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "Le rendement"))
        self.label32.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "ηméc"))
        self.label_37.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "%"))
        self.pushButton_2.setText(_translate("Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE", "RETOUR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE = QtWidgets.QWidget()
    ui = Ui_Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE()
    ui.setupUi(Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE)
    Denture_droite_deporteEX_VARIATION_ANT_NON_IMPOSE.show()
    sys.exit(app.exec_())
