
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Denture_droite_deporteE(object):
    def setupUi(self, Denture_droite_deporteE):
        Denture_droite_deporteE.setObjectName("Denture_droite_deporteE")
        Denture_droite_deporteE.resize(537, 993)
        self.gridLayout = QtWidgets.QGridLayout(Denture_droite_deporteE)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(Denture_droite_deporteE)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 595, 966))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 2, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 1, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.gridLayout_2.addWidget(self.label_46, 2, 3, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.gridLayout_2.addWidget(self.label_48, 3, 3, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.gridLayout_2.addWidget(self.label_47, 3, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 0, 1, 1, 1)
        self.lineEdit_12_module = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module.setFont(font)
        self.lineEdit_12_module.setObjectName("lineEdit_12_module")
        self.gridLayout_2.addWidget(self.lineEdit_12_module, 2, 2, 1, 1)
        self.lineEdit_12_module_7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_7.setFont(font)
        self.lineEdit_12_module_7.setObjectName("lineEdit_12_module_7")
        self.gridLayout_2.addWidget(self.lineEdit_12_module_7, 3, 2, 1, 1)
        self.lineEdit_12_module_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_3.setFont(font)
        self.lineEdit_12_module_3.setObjectName("lineEdit_12_module_3")
        self.gridLayout_2.addWidget(self.lineEdit_12_module_3, 1, 2, 1, 1)
        self.lineEdit_12_module_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_2.setFont(font)
        self.lineEdit_12_module_2.setObjectName("lineEdit_12_module_2")
        self.gridLayout_2.addWidget(self.lineEdit_12_module_2, 0, 2, 1, 1)
        self.lineEdit_12_module_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_4.setFont(font)
        self.lineEdit_12_module_4.setObjectName("lineEdit_12_module_4")
        self.gridLayout_2.addWidget(self.lineEdit_12_module_4, 2, 4, 1, 1)
        self.lineEdit_12_module_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_6.setFont(font)
        self.lineEdit_12_module_6.setObjectName("lineEdit_12_module_6")
        self.gridLayout_2.addWidget(self.lineEdit_12_module_6, 3, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setMaximumSize(QtCore.QSize(180, 180))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.label_45 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.verticalLayout.addWidget(self.label_45, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_29 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 20, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 15, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 10, 0, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_71.setFont(font)
        self.label_71.setObjectName("label_71")
        self.gridLayout_3.addWidget(self.label_71, 7, 3, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_70.setFont(font)
        self.label_70.setObjectName("label_70")
        self.gridLayout_3.addWidget(self.label_70, 6, 3, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 19, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 13, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 11, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 14, 0, 1, 1)
        self.lineEdit_12_module_13 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_13.setFont(font)
        self.lineEdit_12_module_13.setObjectName("lineEdit_12_module_13")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_13, 13, 2, 1, 1)
        self.lineEdit_12_module_15 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_15.setFont(font)
        self.lineEdit_12_module_15.setObjectName("lineEdit_12_module_15")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_15, 12, 2, 1, 1)
        self.lineEdit_12_module_21 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_21.setFont(font)
        self.lineEdit_12_module_21.setObjectName("lineEdit_12_module_21")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_21, 9, 2, 1, 1)
        self.lineEdit_12_module_14 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_14.setFont(font)
        self.lineEdit_12_module_14.setObjectName("lineEdit_12_module_14")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_14, 14, 2, 1, 1)
        self.lineEdit_12_module_20 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_20.setFont(font)
        self.lineEdit_12_module_20.setObjectName("lineEdit_12_module_20")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_20, 6, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 9, 0, 1, 1)
        self.lineEdit_12_module_17 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_17.setFont(font)
        self.lineEdit_12_module_17.setObjectName("lineEdit_12_module_17")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_17, 8, 2, 1, 1)
        self.lineEdit_12_module_24 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_24.setFont(font)
        self.lineEdit_12_module_24.setObjectName("lineEdit_12_module_24")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_24, 15, 2, 1, 1)
        self.lineEdit_12_module_23 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_23.setFont(font)
        self.lineEdit_12_module_23.setObjectName("lineEdit_12_module_23")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_23, 11, 2, 1, 1)
        self.lineEdit_12_module_26 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_26.setFont(font)
        self.lineEdit_12_module_26.setObjectName("lineEdit_12_module_26")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_26, 10, 2, 1, 1)
        self.lineEdit_12_module_22 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_22.setFont(font)
        self.lineEdit_12_module_22.setObjectName("lineEdit_12_module_22")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_22, 16, 2, 1, 1)
        self.lineEdit_12_module_29 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_29.setFont(font)
        self.lineEdit_12_module_29.setObjectName("lineEdit_12_module_29")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_29, 21, 2, 1, 1)
        self.lineEdit_12_module_30 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_30.setFont(font)
        self.lineEdit_12_module_30.setObjectName("lineEdit_12_module_30")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_30, 19, 2, 1, 1)
        self.lineEdit_12_module_18 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_18.setFont(font)
        self.lineEdit_12_module_18.setObjectName("lineEdit_12_module_18")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_18, 18, 2, 1, 1)
        self.lineEdit_12_module_16 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_16.setFont(font)
        self.lineEdit_12_module_16.setObjectName("lineEdit_12_module_16")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_16, 17, 2, 1, 1)
        self.lineEdit_12_module_27 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_27.setFont(font)
        self.lineEdit_12_module_27.setObjectName("lineEdit_12_module_27")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_27, 23, 2, 1, 1)
        self.lineEdit_12_module_19 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_19.setFont(font)
        self.lineEdit_12_module_19.setObjectName("lineEdit_12_module_19")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_19, 20, 2, 1, 1)
        self.lineEdit_12_module_28 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_28.setFont(font)
        self.lineEdit_12_module_28.setObjectName("lineEdit_12_module_28")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_28, 22, 2, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.gridLayout_3.addWidget(self.label_69, 5, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 8, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 6, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 5, 0, 1, 1)
        self.lineEdit_12_module_10 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_10.setFont(font)
        self.lineEdit_12_module_10.setObjectName("lineEdit_12_module_10")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_10, 3, 2, 1, 1)
        self.lineEdit_12_module_9 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_9.setFont(font)
        self.lineEdit_12_module_9.setObjectName("lineEdit_12_module_9")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_9, 2, 2, 1, 1)
        self.lineEdit_12_module_8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_8.setFont(font)
        self.lineEdit_12_module_8.setObjectName("lineEdit_12_module_8")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_8, 1, 2, 1, 1)
        self.lineEdit_12_module_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_5.setFont(font)
        self.lineEdit_12_module_5.setObjectName("lineEdit_12_module_5")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_5, 0, 2, 1, 1)
        self.lineEdit_12_module_12 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_12.setFont(font)
        self.lineEdit_12_module_12.setObjectName("lineEdit_12_module_12")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_12, 5, 2, 1, 1)
        self.lineEdit_12_module_11 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_11.setFont(font)
        self.lineEdit_12_module_11.setObjectName("lineEdit_12_module_11")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_11, 4, 2, 1, 1)
        self.lineEdit_12_module_25 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_25.setFont(font)
        self.lineEdit_12_module_25.setObjectName("lineEdit_12_module_25")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_25, 7, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 7, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 12, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 16, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 17, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.gridLayout_3.addWidget(self.label_36, 1, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 18, 0, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.gridLayout_3.addWidget(self.label_63, 12, 1, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.gridLayout_3.addWidget(self.label_67, 7, 1, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.gridLayout_3.addWidget(self.label_62, 2, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.gridLayout_3.addWidget(self.label_44, 15, 1, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")
        self.gridLayout_3.addWidget(self.label_68, 6, 1, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.gridLayout_3.addWidget(self.label_50, 3, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.gridLayout_3.addWidget(self.label_43, 16, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.gridLayout_3.addWidget(self.label_58, 17, 1, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.gridLayout_3.addWidget(self.label_60, 5, 1, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.gridLayout_3.addWidget(self.label_61, 4, 1, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.gridLayout_3.addWidget(self.label_49, 9, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.gridLayout_3.addWidget(self.label_53, 10, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.gridLayout_3.addWidget(self.label_41, 11, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.gridLayout_3.addWidget(self.label_59, 8, 1, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_72.setFont(font)
        self.label_72.setObjectName("label_72")
        self.gridLayout_3.addWidget(self.label_72, 8, 3, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.gridLayout_3.addWidget(self.label_55, 9, 3, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.gridLayout_3.addWidget(self.label_56, 10, 3, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_75.setFont(font)
        self.label_75.setObjectName("label_75")
        self.gridLayout_3.addWidget(self.label_75, 14, 3, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_73.setFont(font)
        self.label_73.setObjectName("label_73")
        self.gridLayout_3.addWidget(self.label_73, 11, 3, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_76.setFont(font)
        self.label_76.setObjectName("label_76")
        self.gridLayout_3.addWidget(self.label_76, 15, 3, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_77.setFont(font)
        self.label_77.setObjectName("label_77")
        self.gridLayout_3.addWidget(self.label_77, 16, 3, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_74.setFont(font)
        self.label_74.setObjectName("label_74")
        self.gridLayout_3.addWidget(self.label_74, 13, 3, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_79.setFont(font)
        self.label_79.setObjectName("label_79")
        self.gridLayout_3.addWidget(self.label_79, 18, 3, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_78.setFont(font)
        self.label_78.setObjectName("label_78")
        self.gridLayout_3.addWidget(self.label_78, 17, 3, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_81.setFont(font)
        self.label_81.setObjectName("label_81")
        self.gridLayout_3.addWidget(self.label_81, 21, 3, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 23, 0, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_80.setFont(font)
        self.label_80.setObjectName("label_80")
        self.gridLayout_3.addWidget(self.label_80, 19, 3, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 22, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.gridLayout_3.addWidget(self.label_39, 0, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 21, 0, 1, 1)
        self.lineEdit_12_module_34 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_34.setFont(font)
        self.lineEdit_12_module_34.setObjectName("lineEdit_12_module_34")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_34, 6, 4, 1, 1)
        self.lineEdit_12_module_31 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_31.setFont(font)
        self.lineEdit_12_module_31.setObjectName("lineEdit_12_module_31")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_31, 5, 4, 1, 1)
        self.lineEdit_12_module_35 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_35.setFont(font)
        self.lineEdit_12_module_35.setObjectName("lineEdit_12_module_35")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_35, 7, 4, 1, 1)
        self.lineEdit_12_module_33 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_33.setFont(font)
        self.lineEdit_12_module_33.setObjectName("lineEdit_12_module_33")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_33, 8, 4, 1, 1)
        self.lineEdit_12_module_41 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_41.setFont(font)
        self.lineEdit_12_module_41.setObjectName("lineEdit_12_module_41")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_41, 14, 4, 1, 1)
        self.lineEdit_12_module_38 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_38.setFont(font)
        self.lineEdit_12_module_38.setObjectName("lineEdit_12_module_38")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_38, 9, 4, 1, 1)
        self.lineEdit_12_module_32 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_32.setFont(font)
        self.lineEdit_12_module_32.setObjectName("lineEdit_12_module_32")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_32, 11, 4, 1, 1)
        self.lineEdit_12_module_36 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_36.setFont(font)
        self.lineEdit_12_module_36.setObjectName("lineEdit_12_module_36")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_36, 10, 4, 1, 1)
        self.lineEdit_12_module_39 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_39.setFont(font)
        self.lineEdit_12_module_39.setObjectName("lineEdit_12_module_39")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_39, 16, 4, 1, 1)
        self.lineEdit_12_module_43 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_43.setFont(font)
        self.lineEdit_12_module_43.setObjectName("lineEdit_12_module_43")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_43, 15, 4, 1, 1)
        self.lineEdit_12_module_42 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_42.setFont(font)
        self.lineEdit_12_module_42.setObjectName("lineEdit_12_module_42")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_42, 17, 4, 1, 1)
        self.lineEdit_12_module_37 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_37.setFont(font)
        self.lineEdit_12_module_37.setObjectName("lineEdit_12_module_37")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_37, 13, 4, 1, 1)
        self.lineEdit_12_module_47 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_47.setFont(font)
        self.lineEdit_12_module_47.setObjectName("lineEdit_12_module_47")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_47, 18, 4, 1, 1)
        self.lineEdit_12_module_44 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_44.setFont(font)
        self.lineEdit_12_module_44.setObjectName("lineEdit_12_module_44")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_44, 19, 4, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.gridLayout_3.addWidget(self.label_66, 20, 1, 1, 1)
        self.lineEdit_12_module_45 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module_45.setFont(font)
        self.lineEdit_12_module_45.setObjectName("lineEdit_12_module_45")
        self.gridLayout_3.addWidget(self.lineEdit_12_module_45, 21, 4, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.gridLayout_3.addWidget(self.label_54, 22, 1, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.gridLayout_3.addWidget(self.label_65, 21, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.gridLayout_3.addWidget(self.label_52, 13, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.gridLayout_3.addWidget(self.label_51, 14, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.gridLayout_3.addWidget(self.label_42, 23, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.gridLayout_3.addWidget(self.label_57, 18, 1, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.gridLayout_3.addWidget(self.label_64, 19, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(Denture_droite_deporteE)
        QtCore.QMetaObject.connectSlotsByName(Denture_droite_deporteE)

    def retranslateUi(self, Denture_droite_deporteE):
        _translate = QtCore.QCoreApplication.translate
        Denture_droite_deporteE.setWindowTitle(_translate("Denture_droite_deporteE", "Denture doite deporte exterieur"))
        self.label_2.setText(_translate("Denture_droite_deporteE", "Valeurs d\'entrée"))
        self.label_4.setText(_translate("Denture_droite_deporteE", "Angle de pression normalisé"))
        self.label_3.setText(_translate("Denture_droite_deporteE", "Module normalisé"))
        self.label_6.setText(_translate("Denture_droite_deporteE", "Les déports"))
        self.label_5.setText(_translate("Denture_droite_deporteE", "Nombre de dent"))
        self.label_30.setText(_translate("Denture_droite_deporteE", "Z1"))
        self.label_27.setText(_translate("Denture_droite_deporteE", "∝"))
        self.label_46.setText(_translate("Denture_droite_deporteE", "Z2"))
        self.label_48.setText(_translate("Denture_droite_deporteE", "X2"))
        self.label_47.setText(_translate("Denture_droite_deporteE", "X1"))
        self.label_25.setText(_translate("Denture_droite_deporteE", "m"))
        self.pushButton.setText(_translate("Denture_droite_deporteE", "CALCULEZ"))
        self.label_45.setText(_translate("Denture_droite_deporteE", "Valeurs de sortie"))
        self.label_29.setText(_translate("Denture_droite_deporteE", "Rapport de conduite total"))
        self.label_8.setText(_translate("Denture_droite_deporteE", "Module de fonctionnement"))
        self.label_7.setText(_translate("Denture_droite_deporteE", "Angle de pression de fonctionnement"))
        self.label_10.setText(_translate("Denture_droite_deporteE", "Pas de base"))
        self.label_22.setText(_translate("Denture_droite_deporteE", "Epaisseur curviligne au primitif de fonctionnement"))
        self.label_17.setText(_translate("Denture_droite_deporteE", "Saillie de fonctionnememt"))
        self.label_71.setText(_translate("Denture_droite_deporteE", "da2"))
        self.label_70.setText(_translate("Denture_droite_deporteE", "d2\'"))
        self.label_28.setText(_translate("Denture_droite_deporteE", "Rapport de conduite partiel de retraite "))
        self.label_20.setText(_translate("Denture_droite_deporteE", "Angle de pression de tête"))
        self.label_18.setText(_translate("Denture_droite_deporteE", "Creux de fonctionnement"))
        self.label_21.setText(_translate("Denture_droite_deporteE", "Epaisseur curviligne au primitif"))
        self.label_16.setText(_translate("Denture_droite_deporteE", "Diamètre de base"))
        self.label_69.setText(_translate("Denture_droite_deporteE", "d2"))
        self.label_15.setText(_translate("Denture_droite_deporteE", "Diamètre de pied"))
        self.label_11.setText(_translate("Denture_droite_deporteE", "Entraxe de fonctionnement"))
        self.label_13.setText(_translate("Denture_droite_deporteE", "Diamètre primitif de fonctionnement"))
        self.label_12.setText(_translate("Denture_droite_deporteE", "Diamètre primitif"))
        self.label_14.setText(_translate("Denture_droite_deporteE", "Diamètre de tête"))
        self.label_19.setText(_translate("Denture_droite_deporteE", "Hauteur "))
        self.label_9.setText(_translate("Denture_droite_deporteE", "Pas au primitif"))
        self.label_23.setText(_translate("Denture_droite_deporteE", "Epaisseur curviligne au cercle de tête"))
        self.label_24.setText(_translate("Denture_droite_deporteE", "Epaisseur curviligne au cercle de base"))
        self.label_36.setText(_translate("Denture_droite_deporteE", "m\'"))
        self.label_26.setText(_translate("Denture_droite_deporteE", "Déport de denture"))
        self.label_63.setText(_translate("Denture_droite_deporteE", "h"))
        self.label_67.setText(_translate("Denture_droite_deporteE", "da1"))
        self.label_62.setText(_translate("Denture_droite_deporteE", "p"))
        self.label_44.setText(_translate("Denture_droite_deporteE", "s1\'"))
        self.label_68.setText(_translate("Denture_droite_deporteE", "d1\'"))
        self.label_50.setText(_translate("Denture_droite_deporteE", "pb"))
        self.label_43.setText(_translate("Denture_droite_deporteE", "sa1"))
        self.label_58.setText(_translate("Denture_droite_deporteE", "sb1"))
        self.label_60.setText(_translate("Denture_droite_deporteE", "d1"))
        self.label_61.setText(_translate("Denture_droite_deporteE", "a\'"))
        self.label_49.setText(_translate("Denture_droite_deporteE", "db1"))
        self.label_53.setText(_translate("Denture_droite_deporteE", "ha1"))
        self.label_41.setText(_translate("Denture_droite_deporteE", "hf1"))
        self.label_59.setText(_translate("Denture_droite_deporteE", "df1"))
        self.label_72.setText(_translate("Denture_droite_deporteE", "df2"))
        self.label_55.setText(_translate("Denture_droite_deporteE", "db2"))
        self.label_56.setText(_translate("Denture_droite_deporteE", "ha2"))
        self.label_75.setText(_translate("Denture_droite_deporteE", "s2"))
        self.label_73.setText(_translate("Denture_droite_deporteE", "hf2"))
        self.label_76.setText(_translate("Denture_droite_deporteE", "s2\'"))
        self.label_77.setText(_translate("Denture_droite_deporteE", "sa2"))
        self.label_74.setText(_translate("Denture_droite_deporteE", "∝a2"))
        self.label_79.setText(_translate("Denture_droite_deporteE", "δ2"))
        self.label_78.setText(_translate("Denture_droite_deporteE", "sb2"))
        self.label_81.setText(_translate("Denture_droite_deporteE", "ga2"))
        self.label_33.setText(_translate("Denture_droite_deporteE", "Arc de conduite"))
        self.label_80.setText(_translate("Denture_droite_deporteE", "ε2"))
        self.label_32.setText(_translate("Denture_droite_deporteE", "Longueur totale de conduite"))
        self.label_39.setText(_translate("Denture_droite_deporteE", "∝\'"))
        self.label_31.setText(_translate("Denture_droite_deporteE", "Longueur partielle de retraite"))
        self.label_66.setText(_translate("Denture_droite_deporteE", "ε∝"))
        self.label_54.setText(_translate("Denture_droite_deporteE", "g∝"))
        self.label_65.setText(_translate("Denture_droite_deporteE", "ga1"))
        self.label_52.setText(_translate("Denture_droite_deporteE", "∝a1"))
        self.label_51.setText(_translate("Denture_droite_deporteE", "s1"))
        self.label_42.setText(_translate("Denture_droite_deporteE", "gt"))
        self.label_57.setText(_translate("Denture_droite_deporteE", "δ1"))
        self.label_64.setText(_translate("Denture_droite_deporteE", "ε1"))
        self.pushButton_2.setText(_translate("Denture_droite_deporteE", "RETOUR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Denture_droite_deporteE = QtWidgets.QWidget()
    ui = Ui_Denture_droite_deporteE()
    ui.setupUi(Denture_droite_deporteE)
    Denture_droite_deporteE.show()
    sys.exit(app.exec_())
