
from PyQt5 import QtCore, QtGui, QtWidgets
import math
from PyQt5.QtWidgets import QMessageBox
import openpyxl

class Ui_denture_droite_ch1(object):



    def calculer_engrenage(self):
    
        try:
            A_P = int(self.lineEdit_2_alpha.text())
            M = float(self.lineEdit_12_module.text())    
            Z1 = int(self.lineEdit_7_Z1.text())
            Z2 = int(self.lineEdit_22_Z2.text()) 
            k = float(self.lineEdit_5_k.text())

                    
            U = Z2 / Z1
            i = float(-(Z1 / Z2))
            p = math.pi * M
            Cosinus = math.cos(math.radians(A_P))
            pb = float((p * Cosinus))
            d1 = Z1 * M 
            d2 = Z2 * M
            a = ((d1 + d2) / 2)
            da1 = (d1 + 2 * M) 
            da2 = (d2 + 2 * M)
            df1 = (d1 - 2.5 * M)
            df2 = (d2 - 2.5 * M)
            db1 = (d1 * Cosinus)
            db2 = (d2 * Cosinus)
            Ha = M
            Hf = 1.25 * M
            h = Ha + Hf
            S1 = (math.pi * M) / 2
            I = p - S1
            b = k * M
        except ValueError:
            QMessageBox.warning(None, "Erreur de saisie", "Il est impossible d'effectuer le calcul. Vérifiez les valeurs d'entrée.")
            return

        # Affichage des resultats dans les LineEdit
        self.lineEdit_14_U.setText(str(U))
        self.lineEdit_4_i.setText(str(i))
        self.lineEdit_6_p1.setText(str(p))
        self.lineEdit_24_p2.setText(str(p))
        self.lineEdit_8_Pb.setText(str(pb))
        self.lineEdit_3_d1.setText(str(d1))
        self.lineEdit_25_d2.setText(str(d2))
        self.lineEdit_a.setText(str(a))
        self.lineEdit_11_da1.setText(str(da1))
        self.lineEdit_26_da2.setText(str(da2))
        self.lineEdit_10_df1.setText(str(df1))
        self.lineEdit_27_df2.setText(str(df2))
        self.lineEdit_9_db1.setText(str(db1))
        self.lineEdit_28_db2.setText(str(db2))
        self.lineEdit_19_ha.setText(str(Ha))
        self.lineEdit_15_hf.setText(str(Hf))
        self.lineEdit_16_h.setText(str(h))
        self.lineEdit_18_S1.setText(str(S1))
        self.lineEdit_29_S2.setText(str(S1))
        self.lineEdit_17_e.setText(str(I))
        self.lineEdit_20_b.setText(str(b))

    def sauvegarder_dans_excel(self):
        wb = openpyxl.Workbook()
        ws = wb.active

        noms_labels = [
            self.label_3.text(),
            self.label_4.text(),
            self.label_5.text(),
            self.label_5.text(),
            self.label_7.text(),
            self.label_16.text(),
            self.label_17.text(),
            self.label_8.text(),
            self.label_8.text(),
            self.label_9.text(),
            self.label_10.text(),
            self.label_10.text(),
            self.label_11.text(),
            self.label_12.text(),
            self.label_12.text(),
            self.label_14.text(),
            self.label_14.text(),
            self.label_13.text(),
            self.label_13.text(),
            self.label_15.text(),
            self.label_18.text(),
            self.label_19.text(),
            self.label_20.text(),
            self.label_20.text(),
            self.label_21.text(),
            self.label_23.text()
        ]

        symboles = [
            'm', '∝', 'Z1', 'Z2', 'K', 'U', 'i', 'p1',
            'p2', 'pb', 'd1', 'd2', 'a', 'da1', 'da2', 'df1',
            'df2', 'db1', 'db2', 'ha', 'hf', 'h', 'S1', 'S2', 'e', 'b'
        ]


        valeurs = [
            self.lineEdit_12_module.text(),
            self.lineEdit_2_alpha.text(),
            self.lineEdit_7_Z1.text(),
            self.lineEdit_22_Z2.text(),
            self.lineEdit_5_k.text(),
            self.lineEdit_14_U.text(),
            self.lineEdit_4_i.text(),
            self.lineEdit_6_p1.text(),
            self.lineEdit_24_p2.text(),
            self.lineEdit_8_Pb.text(),
            self.lineEdit_3_d1.text(),
            self.lineEdit_25_d2.text(),
            self.lineEdit_a.text(),
            self.lineEdit_11_da1.text(),
            self.lineEdit_26_da2.text(),
            self.lineEdit_10_df1.text(),
            self.lineEdit_27_df2.text(),
            self.lineEdit_9_db1.text(),
            self.lineEdit_28_db2.text(),
            self.lineEdit_19_ha.text(),
            self.lineEdit_15_hf.text(),
            self.lineEdit_16_h.text(),
            self.lineEdit_18_S1.text(),
            self.lineEdit_29_S2.text(),
            self.lineEdit_17_e.text(),
            self.lineEdit_20_b.text(),
        ]

        unites = ['mm', 'degré', '', '', '', '', '', 'mm', 'mm', 'mm', 'mm', 'mm', 'mm', 'mm', 'mm', 'mm', 'mm', 'mm', 'mm',
            'mm', 'mm', 'mm', 'mm', 'mm', 'mm', 'mm',

        ]

        entete = ['Nom(s)', 'Symbole(s)', 'Valeur(s)', 'Unité(s)']
        ws.append(entete)

        for i in range(len(noms_labels)):
            ws.append([noms_labels[i], symboles[i], valeurs[i], unites[i]])

        for row in ws.iter_rows(min_row=1, max_row=27, min_col=1, max_col=4):
            for cell in row:
                cell.border = openpyxl.styles.Border(
                    left=openpyxl.styles.Side(border_style='thin'),
                    right=openpyxl.styles.Side(border_style='thin'),
                    top=openpyxl.styles.Side(border_style='thin'),
                    bottom=openpyxl.styles.Side(border_style='thin')
                )

        for row in ws.iter_rows(min_row=1, max_row=1, min_col=1, max_col=4):
            for cell in row:
                cell.fill = openpyxl.styles.PatternFill(start_color="0070C0", end_color="0070C0", fill_type="solid")
                cell.font = openpyxl.styles.Font(color="FFFFFF", bold=True)


        file_path, _ = QtWidgets.QFileDialog.getSaveFileName(None, "Enregistrer le fichier Excel", "", "Excel Files (*.xlsx)")
        if file_path:
            wb.save(file_path)
            QtWidgets.QMessageBox.information(None, "Enregistrement", "Fichier Excel enregistré avec succès !")

    def setupUi(self, denture_droite_ch1):
        denture_droite_ch1.setObjectName("denture_droite_ch1")
        denture_droite_ch1.resize(494, 394)

        denture_droite_ch1.setWindowModality(QtCore.Qt.WindowModal)
        denture_droite_ch1.setStyleSheet("background-color: #ebebeb;")

        self.gridLayout_4 = QtWidgets.QGridLayout(denture_droite_ch1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(denture_droite_ch1)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 467, 846))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 2, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        ###############################################
        self.pushButton_2.setStyleSheet("background-color: #ff557f;")

        self.gridLayout_3.addWidget(self.pushButton_2, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.label_2.setStyleSheet("background-color: #00ff7f;")
        #################################################################

        self.verticalLayout_4.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_5_k = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_5_k.setFont(font)
        self.lineEdit_5_k.setText("")
        self.lineEdit_5_k.setObjectName("lineEdit_5_k")
        self.gridLayout_2.addWidget(self.lineEdit_5_k, 4, 1, 1, 1)
        self.lineEdit_7_Z1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_7_Z1.setFont(font)
        self.lineEdit_7_Z1.setObjectName("lineEdit_7_Z1")
        self.gridLayout_2.addWidget(self.lineEdit_7_Z1, 2, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_34 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.gridLayout_2.addWidget(self.label_34, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_13_N1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_13_N1.setFont(font)
        self.lineEdit_13_N1.setObjectName("lineEdit_13_N1")
        self.gridLayout_2.addWidget(self.lineEdit_13_N1, 3, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout_2.addWidget(self.label_33, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_25 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEdit_12_module = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_12_module.setFont(font)
        self.lineEdit_12_module.setObjectName("lineEdit_12_module")
        self.gridLayout_2.addWidget(self.lineEdit_12_module, 0, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 1, 0, 1, 1)
        self.lineEdit_2_alpha = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2_alpha.setFont(font)
        self.lineEdit_2_alpha.setObjectName("lineEdit_2_alpha")
        self.gridLayout_2.addWidget(self.lineEdit_2_alpha, 1, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.gridLayout_2.addWidget(self.label_46, 2, 2, 1, 1)
        self.lineEdit_23_N2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_23_N2.setFont(font)
        self.lineEdit_23_N2.setObjectName("lineEdit_23_N2")
        self.gridLayout_2.addWidget(self.lineEdit_23_N2, 3, 3, 1, 1)
        self.lineEdit_22_Z2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_22_Z2.setFont(font)
        self.lineEdit_22_Z2.setObjectName("lineEdit_22_Z2")
        self.gridLayout_2.addWidget(self.lineEdit_22_Z2, 2, 3, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.gridLayout_2.addWidget(self.label_47, 3, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton.setMaximumSize(QtCore.QSize(180, 180))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.calculer_engrenage) # Liaison du clic du bouton à la fonction de calcul
        self.pushButton.setStyleSheet("background-color: #55aaff;")
        ###################################################################################################

        self.verticalLayout_6.addWidget(self.pushButton, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem3)
        self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")

        #####################################################################################################
        self.pushButton_3.clicked.connect(self.sauvegarder_dans_excel)  # Connecte le clic du bouton à la fonction de sauvegarde
        self.pushButton_3.setStyleSheet("background-color: #55aaff;")

        self.verticalLayout_6.addWidget(self.pushButton_3, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem4)
        self.label_45 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")

        self.label_45.setStyleSheet("background-color: #00ff7f;")
        ##########################################################3

        self.verticalLayout_7.addWidget(self.label_45, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_2.addWidget(self.label_17)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_2.addWidget(self.label_14)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_2.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_2.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_2.addWidget(self.label_21)
        self.label_23 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_2.addWidget(self.label_23)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_48 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.gridLayout.addWidget(self.label_48, 2, 2, 1, 1)
        self.lineEdit_24_p2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_24_p2.setFont(font)
        self.lineEdit_24_p2.setObjectName("lineEdit_24_p2")
        self.gridLayout.addWidget(self.lineEdit_24_p2, 2, 3, 1, 1)
        self.lineEdit_20_b = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_20_b.setFont(font)
        self.lineEdit_20_b.setObjectName("lineEdit_20_b")
        self.gridLayout.addWidget(self.lineEdit_20_b, 14, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 13, 0, 1, 1)
        self.lineEdit_9_db1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_9_db1.setFont(font)
        self.lineEdit_9_db1.setObjectName("lineEdit_9_db1")
        self.gridLayout.addWidget(self.lineEdit_9_db1, 8, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 3, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 1, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 0, 0, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.gridLayout.addWidget(self.label_35, 2, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.gridLayout.addWidget(self.label_36, 12, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.gridLayout.addWidget(self.label_37, 6, 0, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.gridLayout.addWidget(self.label_39, 7, 0, 1, 1)
        self.lineEdit_17_e = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_17_e.setFont(font)
        self.lineEdit_17_e.setObjectName("lineEdit_17_e")
        self.gridLayout.addWidget(self.lineEdit_17_e, 13, 1, 1, 1)
        self.lineEdit_15_hf = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_15_hf.setFont(font)
        self.lineEdit_15_hf.setObjectName("lineEdit_15_hf")
        self.gridLayout.addWidget(self.lineEdit_15_hf, 10, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.gridLayout.addWidget(self.label_38, 4, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.gridLayout.addWidget(self.label_42, 5, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.gridLayout.addWidget(self.label_40, 10, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.gridLayout.addWidget(self.label_41, 11, 0, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.gridLayout.addWidget(self.label_44, 9, 0, 1, 1)
        self.lineEdit_18_S1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_18_S1.setFont(font)
        self.lineEdit_18_S1.setObjectName("lineEdit_18_S1")
        self.gridLayout.addWidget(self.lineEdit_18_S1, 12, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.gridLayout.addWidget(self.label_43, 8, 0, 1, 1)
        self.lineEdit_19_ha = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_19_ha.setFont(font)
        self.lineEdit_19_ha.setObjectName("lineEdit_19_ha")
        self.gridLayout.addWidget(self.lineEdit_19_ha, 9, 1, 1, 1)
        self.lineEdit_16_h = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_16_h.setFont(font)
        self.lineEdit_16_h.setObjectName("lineEdit_16_h")
        self.gridLayout.addWidget(self.lineEdit_16_h, 11, 1, 1, 1)
        self.lineEdit_a = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_a.setFont(font)
        self.lineEdit_a.setObjectName("lineEdit_a")
        self.gridLayout.addWidget(self.lineEdit_a, 5, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 14, 0, 1, 1)
        self.lineEdit_10_df1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_10_df1.setFont(font)
        self.lineEdit_10_df1.setObjectName("lineEdit_10_df1")
        self.gridLayout.addWidget(self.lineEdit_10_df1, 7, 1, 1, 1)
        self.lineEdit_4_i = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_4_i.setFont(font)
        self.lineEdit_4_i.setObjectName("lineEdit_4_i")
        self.gridLayout.addWidget(self.lineEdit_4_i, 1, 1, 1, 1)
        self.lineEdit_8_Pb = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_8_Pb.setFont(font)
        self.lineEdit_8_Pb.setObjectName("lineEdit_8_Pb")
        self.gridLayout.addWidget(self.lineEdit_8_Pb, 3, 1, 1, 1)
        self.lineEdit_14_U = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_14_U.setFont(font)
        self.lineEdit_14_U.setObjectName("lineEdit_14_U")
        self.gridLayout.addWidget(self.lineEdit_14_U, 0, 1, 1, 1)
        self.lineEdit_3_d1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3_d1.setFont(font)
        self.lineEdit_3_d1.setObjectName("lineEdit_3_d1")
        self.gridLayout.addWidget(self.lineEdit_3_d1, 4, 1, 1, 1)
        self.lineEdit_6_p1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_6_p1.setFont(font)
        self.lineEdit_6_p1.setObjectName("lineEdit_6_p1")
        self.gridLayout.addWidget(self.lineEdit_6_p1, 2, 1, 1, 1)
        self.lineEdit_11_da1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_11_da1.setFont(font)
        self.lineEdit_11_da1.setObjectName("lineEdit_11_da1")
        self.gridLayout.addWidget(self.lineEdit_11_da1, 6, 1, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.gridLayout.addWidget(self.label_49, 4, 2, 1, 1)
        self.lineEdit_25_d2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_25_d2.setFont(font)
        self.lineEdit_25_d2.setObjectName("lineEdit_25_d2")
        self.gridLayout.addWidget(self.lineEdit_25_d2, 4, 3, 1, 1)
        self.lineEdit_26_da2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_26_da2.setFont(font)
        self.lineEdit_26_da2.setObjectName("lineEdit_26_da2")
        self.gridLayout.addWidget(self.lineEdit_26_da2, 6, 3, 1, 1)
        self.lineEdit_27_df2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_27_df2.setFont(font)
        self.lineEdit_27_df2.setObjectName("lineEdit_27_df2")
        self.gridLayout.addWidget(self.lineEdit_27_df2, 7, 3, 1, 1)
        self.lineEdit_28_db2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_28_db2.setFont(font)
        self.lineEdit_28_db2.setObjectName("lineEdit_28_db2")
        self.gridLayout.addWidget(self.lineEdit_28_db2, 8, 3, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.gridLayout.addWidget(self.label_51, 6, 2, 1, 1)
        self.lineEdit_29_S2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_29_S2.setFont(font)
        self.lineEdit_29_S2.setObjectName("lineEdit_29_S2")
        self.gridLayout.addWidget(self.lineEdit_29_S2, 12, 3, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.gridLayout.addWidget(self.label_52, 7, 2, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.gridLayout.addWidget(self.label_54, 12, 2, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.gridLayout.addWidget(self.label_53, 8, 2, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.gridLayout_3.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(denture_droite_ch1)
        QtCore.QMetaObject.connectSlotsByName(denture_droite_ch1)



        line_edits = [
            self.lineEdit_12_module,self.lineEdit_2_alpha,self.lineEdit_7_Z1,
            self.lineEdit_22_Z2,self.lineEdit_5_k,self.lineEdit_14_U,
            self.lineEdit_4_i,self.lineEdit_6_p1,self.lineEdit_24_p2,
            self.lineEdit_8_Pb,self.lineEdit_3_d1,self.lineEdit_25_d2,
            self.lineEdit_a,self.lineEdit_11_da1,self.lineEdit_26_da2,
            self.lineEdit_10_df1,self.lineEdit_27_df2,self.lineEdit_9_db1,
            self.lineEdit_28_db2,self.lineEdit_19_ha,self.lineEdit_15_hf,
            self.lineEdit_16_h,self.lineEdit_18_S1,self.lineEdit_29_S2,
            self.lineEdit_17_e,self.lineEdit_20_b,self.lineEdit_13_N1,self.lineEdit_23_N2  
        ]  

        for line_edit in line_edits:
            line_edit.setStyleSheet("background-color: white;")

    def retranslateUi(self, denture_droite_ch1):
        _translate = QtCore.QCoreApplication.translate
        denture_droite_ch1.setWindowTitle(_translate("denture_droite_ch1", "Denture droite"))
        self.pushButton_2.setText(_translate("denture_droite_ch1", "RETOUR"))
        self.label_2.setText(_translate("denture_droite_ch1", "Valeurs d\'entrée"))
        self.label_3.setText(_translate("denture_droite_ch1", "Module"))
        self.label_4.setText(_translate("denture_droite_ch1", "Angle de pression"))
        self.label_5.setText(_translate("denture_droite_ch1", "Nombre de dent"))
        self.label_6.setText(_translate("denture_droite_ch1", "Nombre de tr/mn"))
        self.label_7.setText(_translate("denture_droite_ch1", "Valeur de k"))
        self.label_30.setText(_translate("denture_droite_ch1", "Z1"))
        self.label_34.setText(_translate("denture_droite_ch1", "k"))
        self.label_33.setText(_translate("denture_droite_ch1", "N1"))
        self.label_25.setText(_translate("denture_droite_ch1", "m"))
        self.label_27.setText(_translate("denture_droite_ch1", "∝"))
        self.label_46.setText(_translate("denture_droite_ch1", "Z2"))
        self.label_47.setText(_translate("denture_droite_ch1", "N2"))
        self.pushButton.setText(_translate("denture_droite_ch1", "CALCULEZ"))
        self.pushButton_3.setText(_translate("denture_droite_ch1", "SAUVEGARDER LES RESULTATS DU CALCUL"))
        self.label_45.setText(_translate("denture_droite_ch1", "Valeurs de sortie"))
        self.label_16.setText(_translate("denture_droite_ch1", "Rapport d\'engrenage"))
        self.label_17.setText(_translate("denture_droite_ch1", "Rapport de transmission"))
        self.label_8.setText(_translate("denture_droite_ch1", "Pas au primitif"))
        self.label_9.setText(_translate("denture_droite_ch1", "Pas de base"))
        self.label_10.setText(_translate("denture_droite_ch1", "Diamètre primitif"))
        self.label_11.setText(_translate("denture_droite_ch1", "Entraxe entre les deux roues"))
        self.label_12.setText(_translate("denture_droite_ch1", "Diamètre de tête"))
        self.label_14.setText(_translate("denture_droite_ch1", "Diamètre de pied"))
        self.label_13.setText(_translate("denture_droite_ch1", "Diamètre de base"))
        self.label_15.setText(_translate("denture_droite_ch1", "Saillie"))
        self.label_18.setText(_translate("denture_droite_ch1", "Creux"))
        self.label_19.setText(_translate("denture_droite_ch1", "Hauteur de la dent"))
        self.label_20.setText(_translate("denture_droite_ch1", "Epaisseur de la dent"))
        self.label_21.setText(_translate("denture_droite_ch1", "Intervalle"))
        self.label_23.setText(_translate("denture_droite_ch1", "Largeur de la dent"))
        self.label_48.setText(_translate("denture_droite_ch1", "P2"))
        self.label_28.setText(_translate("denture_droite_ch1", "e"))
        self.label_29.setText(_translate("denture_droite_ch1", "Pb"))
        self.label_31.setText(_translate("denture_droite_ch1", "i"))
        self.label_32.setText(_translate("denture_droite_ch1", "U"))
        self.label_35.setText(_translate("denture_droite_ch1", "P1"))
        self.label_36.setText(_translate("denture_droite_ch1", "S1"))
        self.label_37.setText(_translate("denture_droite_ch1", "da1"))
        self.label_39.setText(_translate("denture_droite_ch1", "df1"))
        self.label_38.setText(_translate("denture_droite_ch1", "d1"))
        self.label_42.setText(_translate("denture_droite_ch1", "a"))
        self.label_40.setText(_translate("denture_droite_ch1", "hf"))
        self.label_41.setText(_translate("denture_droite_ch1", "h"))
        self.label_44.setText(_translate("denture_droite_ch1", "ha"))
        self.label_43.setText(_translate("denture_droite_ch1", "db1"))
        self.label_24.setText(_translate("denture_droite_ch1", "b"))
        self.label_49.setText(_translate("denture_droite_ch1", "d2"))
        self.label_51.setText(_translate("denture_droite_ch1", "da2"))
        self.label_52.setText(_translate("denture_droite_ch1", "df2"))
        self.label_54.setText(_translate("denture_droite_ch1", "s2"))
        self.label_53.setText(_translate("denture_droite_ch1", "db2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    denture_droite_ch1 = QtWidgets.QWidget()
    ui = Ui_denture_droite_ch1()
    ui.setupUi(denture_droite_ch1)
    denture_droite_ch1.show()
    sys.exit(app.exec_())
